// DO NOT EDIT MANUALLY
// This file was automatically generated by `processing/steps/generateTypes.ts`
// To update, run `docker compose up processing` with ENV=development

export const topicIds = [
  'roads_bikelanes',
  'bikeroutes',
  'bicycleParking',
  'trafficSigns',
  'boundaries',
  'places',
  'publicTransport',
  'poiClassification',
  'barriers',
  'landcover',
  'parking',
  // (oxlint: one line per entry)
] as const
export type TopicId = (typeof topicIds)[number]

export type TopicSchedule = 'nightly' | 'weekend'

export const topicScheduleById = {
  roads_bikelanes: 'nightly',
  bikeroutes: 'nightly',
  bicycleParking: 'nightly',
  trafficSigns: 'nightly',
  boundaries: 'nightly',
  places: 'nightly',
  publicTransport: 'nightly',
  poiClassification: 'nightly',
  barriers: 'nightly',
  landcover: 'weekend',
  parking: 'nightly',
} as const satisfies Record<TopicId, TopicSchedule>
