import { existsSync } from 'node:fs'
import { join } from 'node:path'
import { fileURLToPath } from 'node:url'
import { $ } from 'bun'
import { TYPES_DIR } from '../constants/directories.const'
import { topicsConfig } from '../constants/topics.const'
import { params } from '../utils/parameters'

/**
 * Generate types based on the processing tables.
 */
export async function generateTypes() {
  // Only generate type when in development
  if (params.environment !== 'development') return

  console.log('[DEV] Generating types...')

  await writeTopicIdTypes()
  await writeTodoIdTypes()

  await autoformatTypeFiles()
}

async function writeTopicIdTypes() {
  const topicIds = Array.from(topicsConfig.keys())
  const formatStringArray = (values: string[]) => {
    if (values.length === 0) return '\n  // (oxlint: one line per entry)\n'
    return `\n  ${values.map((name) => `'${name}'`).join(',\n  ')}\n  // (oxlint: one line per entry)\n`
  }

  const scheduleEntries = topicIds
    .map((topicId) => `  ${topicId}: '${topicsConfig.get(topicId)!.schedule}'`)
    .join(',\n')

  const fileContent = `
  export const topicIds = [${formatStringArray(topicIds)}] as const
  export type TopicId = (typeof topicIds)[number]

  export type TopicSchedule = 'nightly' | 'weekend'

  export const topicScheduleById = {
  ${scheduleEntries},
  } as const satisfies Record<TopicId, TopicSchedule>
  `

  const typeFile = join(TYPES_DIR, 'topicId.generated.const.ts')
  const content = prefixGeneratedFiles(fileContent)
  await Bun.write(typeFile, content)
}

async function callLuaForNames(luaFilename: 'extract_bikelane_todos' | 'extract_road_todos') {
  try {
    const rawResult = await $`lua /processing/utils/types/${luaFilename}.lua`.text()
    const lines = rawResult.split('\n').filter(Boolean).sort()
    const result = lines.flatMap((line) => {
      const [id, todoTableOnly] = line.split(';')
      if (!id || todoTableOnly === undefined) return []
      return [{ id, todoTableOnly: JSON.parse(todoTableOnly) as boolean }]
    })
    return result
  } catch (error) {
    throw new Error(`[DEV] Failed to get names for "${luaFilename}": ${error}`)
  }
}

// The sort here is also the sort in the dropdown of the subcategory.
function sortMapillarySpecial(a: string, b: string) {
  // Remove __mapillary for base comparison
  const baseA = a.replace(/__mapillary$/, '')
  const baseB = b.replace(/__mapillary$/, '')
  if (baseA === baseB) {
    // If both are the same base, non-mapillary comes first
    if (a.endsWith('__mapillary')) return 1
    if (b.endsWith('__mapillary')) return -1
    return 0
  }
  return baseA < baseB ? -1 : 1
}

async function writeTodoIdTypes() {
  const typeFilePath = join(TYPES_DIR, 'todoId.generated.const.ts')

  const bikelaneTodoNames = await callLuaForNames('extract_bikelane_todos')
  const roadTodoNames = await callLuaForNames('extract_road_todos')
  const todos = [...bikelaneTodoNames, ...roadTodoNames].map((e) => e.id).sort(sortMapillarySpecial)

  const formatStringArray = (values: string[]) => {
    if (values.length === 0) return '\n  // (oxlint: one line per entry)\n'
    return `\n  ${values.map((name) => `'${name}'`).join(',\n  ')}\n  // (oxlint: one line per entry)\n`
  }

  const fileContent = `
export const todoIds = [${formatStringArray(todos)}] as const
export type TodoId = (typeof todoIds)[number]
`

  const content = prefixGeneratedFiles(fileContent)
  await Bun.write(typeFilePath, content)
}

function prefixGeneratedFiles(content: string) {
  return `// DO NOT EDIT MANUALLY
// This file was automatically generated by \`processing/steps/generateTypes.ts\`
// To update, run \`docker compose up processing\` with ENV=development

${content}
`
}

function resolveOxfmtConfigPath() {
  if (existsSync('/mnt/oxfmt.config.mjs')) return '/mnt/oxfmt.config.mjs'
  const besideProcessing = fileURLToPath(new URL('../oxfmt.config.mjs', import.meta.url))
  if (existsSync(besideProcessing)) return besideProcessing
  const repoApp = fileURLToPath(new URL('../../app/oxfmt.config.mjs', import.meta.url))
  if (existsSync(repoApp)) return repoApp
  throw new Error(
    'oxfmt.config.mjs not found (expected /mnt/oxfmt.config.mjs, processing/oxfmt.config.mjs, or app/oxfmt.config.mjs)',
  )
}

async function autoformatTypeFiles() {
  try {
    const oxfmtConfig = resolveOxfmtConfigPath()
    await $`bunx oxfmt --write -c ${oxfmtConfig} ${TYPES_DIR}`
  } catch (error) {
    throw new Error(`Failed to run oxfmt on auto generated types: ${error}`)
  }
}
