// DO NOT EDIT MANUALLY
// This file was automatically generated by `scripts/MapboxStyles/process.ts`

import type { MapboxStyleLayer } from '../types'

export const mapboxStyleGroupLayers_atlas_barriers__area: MapboxStyleLayer[] = [
  {
    id: 'barriers_water_aerodrome2',
    type: 'fill',
    beforeId: 'atlas-app-beforeid-below-road',
    paint: {
      'fill-opacity': 0.42,
    },
  },
  {
    id: 'barriers_water_aerodrome',
    type: 'fill',
    beforeId: 'atlas-app-beforeid-below-road',
    paint: {
      'fill-opacity': 0.5,
      'fill-pattern': 'cross-hatch-barriers',
      'fill-translate': [0, 0],
    },
  },
]
