describe('sanitize_poi_classification_tags', function()
  local S = require('topics.poiClassification.helper.sanitize_poi_classification_tags')
  local exit_processing = require('topics.poiClassification.helper.exit_processing')
  local result_tags = require('topics.poiClassification.helper.result_tags')

  it('is_allowed_import_value uses exact tag values only', function()
    assert.is_true(S.is_allowed_import_value('cafe'))
    assert.is_false(S.is_allowed_import_value('beauty'))
    assert.is_false(S.is_allowed_import_value(nil))
  end)

  it('resolve_category applies shop aliases', function()
    assert.are.equal(S.resolve_category('beauty'), 'Einkauf')
    assert.are.equal(S.resolve_category('cafe'), 'Freizeit')
    assert.is_nil(S.resolve_category('obscure_shop'))
  end)

  it('type_suffix keeps listed shop values and falls back for unknown shops', function()
    assert.are.equal(S.type_suffix('shop', 'supermarket'), 'supermarket')
    assert.are.equal(S.type_suffix('shop', 'beauty'), 'beauty')
    assert.are.equal(S.type_suffix('shop', 'obscure_shop'), 'fallback')
  end)

  it('type_suffix uses exact keys for amenity and falls back otherwise', function()
    assert.are.equal(S.type_suffix('amenity', 'cafe'), 'cafe')
    assert.are.equal(S.type_suffix('amenity', 'bench'), 'fallback')
  end)

  it('exit_processing does not import alias-only amenity values', function()
    local should_skip = exit_processing({ tags = { amenity = 'beauty' } })
    assert.is_true(should_skip)
  end)

  it('exit_processing imports shop=* regardless of shop value', function()
    local should_skip = exit_processing({ tags = { shop = 'obscure_shop' } })
    assert.is_false(should_skip)
  end)

  it('result_tags maps unknown shops to shop-fallback', function()
    local cleaned_tags = result_tags({ tags = { shop = 'obscure_shop' } })
    assert.are.equal(cleaned_tags.type, 'shop-fallback')
    assert.are.equal(cleaned_tags.category, 'Einkauf')
  end)

  it('result_tags keeps listed shop type strings', function()
    local cleaned_tags = result_tags({ tags = { shop = 'supermarket' } })
    assert.are.equal(cleaned_tags.type, 'shop-supermarket')
  end)

  it('combined shop and unknown amenity uses amenity-fallback for type', function()
    local cleaned_tags = result_tags({ tags = { shop = 'convenience', amenity = 'bench' } })
    assert.are.equal(cleaned_tags.type, 'amenity-fallback')
    assert.is_nil(cleaned_tags.category)
  end)
end)
