import { existsSync, writeFileSync } from 'node:fs'
import {
  applyDevPortSlotToProcessEnv,
  exitOnInvalidDevPortSlot,
  isDevPortSlotMode,
} from './devPortSlot'
import { resolveRunningAttachStack } from './devStackDiscovery'
import {
  composeContainerPrefixFromStackId,
  publishedHostPorts,
  stackIdFromRepoRoot,
} from './devStackPorts'
import { envPath, repoRootFromApp } from './ensureEnv'
import {
  currentGitBranch,
  envLocalPath,
  isFeatureBranch,
  isLinkedWorktree,
  syncEnvLocalForBranch,
  usesIsolatedDevStack,
} from './envLocalBranch'
import { stripLegacyPortsFromEnvLocal } from './envLocalLegacy'
import { logErr, logOk, logWarn } from './predevLog'

const label = 'ensure_dev_stack'

function formatEnvLocal(values: Record<string, string>) {
  const lines = [
    '# Auto-generated by predev — worktree-specific Docker stack id.',
    '# Do not commit. Regenerated when missing.',
    `# DEV_STACK_BRANCH=${values.DEV_STACK_BRANCH}`,
    '',
    `DEV_STACK_ID=${values.DEV_STACK_ID}`,
  ]
  if (values.DEV_ATTACH_STACK) {
    lines.push(`DEV_ATTACH_STACK=${values.DEV_ATTACH_STACK}`)
  }
  return `${lines.join('\n')}\n`
}

export async function ensureDevStack() {
  exitOnInvalidDevPortSlot(label)
  const { databasePort, tilesPort, vitePort } = applyDevPortSlotToProcessEnv()
  const repoRoot = repoRootFromApp()
  const localPath = envLocalPath(repoRoot)

  if (!existsSync(envPath(repoRoot))) {
    logErr(label, '.env missing — run ensureEnv first')
    process.exit(1)
  }

  const branch = await currentGitBranch(repoRoot)
  const linkedWorktree = await isLinkedWorktree(repoRoot)
  const sync = await syncEnvLocalForBranch(repoRoot)
  if (sync.action === 'removed_on_default_branch') {
    logWarn(label, 'Removed .env.local on develop/main')
  } else if (sync.action === 'removed_on_main_checkout') {
    logWarn(label, 'Removed .env.local — main checkout uses the default stack')
  } else if (sync.action === 'stale_removed') {
    logWarn(label, `Removed stale .env.local for branch ${sync.branch}`)
  } else if (sync.action === 'env_example_restored') {
    logWarn(label, 'Restored .env.example on develop/main')
  }

  if (!usesIsolatedDevStack(branch, linkedWorktree)) {
    if (isFeatureBranch(branch) && !linkedWorktree) {
      logWarn(
        label,
        `Feature branches should use a worktree, not the main checkout. Run: bun run setup-worktree -- ${branch} — see docs/docker-local-development.md`,
      )
    }
    logOk(label)
    return
  }

  if (existsSync(localPath)) {
    stripLegacyPortsFromEnvLocal(localPath)
    logOk(label)
    return
  }

  const attachFromEnv = process.env.DEV_ATTACH_STACK?.trim() || undefined
  const stackId = stackIdFromRepoRoot(repoRoot)

  if (attachFromEnv) {
    await resolveRunningAttachStack(attachFromEnv)
    logWarn(label, `Attaching to stack "${attachFromEnv}"`)
  } else if (isDevPortSlotMode()) {
    logWarn(
      label,
      `Isolated stack ${stackId} (port slot ${process.env.DEV_PORT_SLOT}: ${databasePort}/${tilesPort}/${vitePort})`,
    )
  } else {
    logWarn(label, `Isolated stack ${stackId} (host ports ${databasePort}/${tilesPort})`)
  }

  const content = formatEnvLocal({
    DEV_STACK_BRANCH: branch,
    DEV_STACK_ID: stackId,
    ...(attachFromEnv ? { DEV_ATTACH_STACK: attachFromEnv } : {}),
  })

  writeFileSync(localPath, content)
  logOk(`${label} (wrote ${localPath})`)
}

export function isAttachMode() {
  return Boolean(process.env.DEV_ATTACH_STACK?.trim())
}

/** This worktree's stack id — used for `docker compose -p`. */
export function devStackIdFromEnv() {
  const stackId = process.env.DEV_STACK_ID?.trim()
  if (stackId) return stackId
  const legacyPrefix = process.env.COMPOSE_DEV_CONTAINER_PREFIX?.trim()
  if (legacyPrefix) return legacyPrefix.replace(/_$/, '')
  return undefined
}

/** Stack whose containers to use (`DEV_ATTACH_STACK` when attaching, else own stack). */
export function dockerStackIdFromEnv() {
  const attach = process.env.DEV_ATTACH_STACK?.trim()
  if (attach === 'default') return undefined
  if (attach) return attach
  return devStackIdFromEnv()
}

/**
 * Compose `-p` project for commands that must join the active stack's network/db.
 * `DEV_ATTACH_STACK=default` uses unprefixed container names (`db` / `tiles`) but the
 * compose project is the develop checkout's folder name (e.g. `tilda-geo`) — not omitted
 * `-p`, which would invent a new project from this worktree path and conflict on `/db`.
 */
export async function dockerComposeProjectFromEnv() {
  const attach = process.env.DEV_ATTACH_STACK?.trim()
  if (attach === 'default') {
    const stack = await resolveRunningAttachStack('default')
    return stack.composeProject
  }
  return dockerStackIdFromEnv()
}

/** Stack id for discovery/stop logic (`default` on develop/main). */
export function activeStackIdFromEnv() {
  const attach = process.env.DEV_ATTACH_STACK?.trim()
  if (attach) return attach
  return devStackIdFromEnv() ?? 'default'
}

/** Runtime-only prefix for `docker-compose.override.yml` container names. */
export function composeContainerPrefixFromEnv() {
  return composeContainerPrefixFromStackId(dockerStackIdFromEnv() ?? '')
}

export async function devStackPortsArePublished() {
  const { databasePort, tilesPort } = applyDevPortSlotToProcessEnv()
  const published = await publishedHostPorts()
  return published.has(databasePort) && published.has(tilesPort)
}

if (import.meta.main) {
  await ensureDevStack()
}
