#!/usr/bin/env bun
import { mkdir, readdir, unlink, writeFile } from 'node:fs/promises'
import path from 'node:path'
import { GPKG_LEGEND_STYLE_IDS, LEGEND_STYLE_IDS } from './lib/types'
import { buildParkbeschraenkungenStyles } from './profiles/parkbeschraenkungen'
import { buildParkingPublicGpkgStyles } from './profiles/parking_public_gpkg'

const scriptDir = import.meta.dir
const outputDir = path.join(scriptDir, 'output')
const masterportalDir = 'masterportal'
const tildaDir = 'tilda'

const parseArgs = () => {
  const args = process.argv.slice(2)
  let zoom = 17
  let outDir = outputDir
  let splitStyles = false

  for (let i = 0; i < args.length; i++) {
    if (args[i] === '--zoom' && args[i + 1]) {
      zoom = Number(args[i + 1])
      i++
    }
    if (args[i] === '--out-dir') {
      const outDirArg = args[i + 1]
      if (outDirArg) {
        outDir = path.resolve(outDirArg)
        i++
      }
    }
    if (args[i] === '--split-styles') {
      splitStyles = true
    }
  }

  return { zoom, outDir, splitStyles }
}

const masterportalReadme = `<!-- Generated by convert.ts — do not edit manually -->

# Masterportal Styles (zum Weitergeben)

Masterportal nutzt **eine** globale \`style.json\` (Array aller Style-Definitionen). Jeder Layer in \`config.json\` verweist per \`styleId\` auf einen Eintrag in dieser Datei — nicht eine Datei pro Layer.

## Dateien

| Datei | Ziel |
|-------|------|
| \`parking_public.gpkg.styles.json\` | **Empfohlen für EUVM-GPKG** (\`scripts/tilda-parkraum-euvm-export\`) — 3 Layer, \`styleId\` = GPKG-Layername |
| \`parkbeschraenkungen.json\` | Volle Tile-Karte (7 Styles) — nur für tilda-geo-Vektorkacheln / Preview |
| \`parkbeschraenkungen-legend.json\` | Legende Tile-Profil |
| \`parking_public.gpkg.legend.json\` | Legende GPKG-Profil |

\`tilda/masterportal-layer-snippet.json\` zeigt die \`styleId\`-Zuordnung pro GPKG-Layer.

Siehe [MASTERPORTAL.md](../MASTERPORTAL.md) — Anleitung für Masterportal-Partner (Einrichtung, Dateizuordnung, Einschränkungen).
`

const tildaReadme = `<!-- Generated by convert.ts — do not edit manually -->

# TILDA Referenz (intern)

| Datei | Inhalt |
|-------|--------|
| \`manifest.json\` | Tile-Preview: URLs, source-layers |
| \`gpkg-manifest.json\` | GPKG-Layer → styleId, Geometrietyp, Hinweise |
| \`masterportal-layer-snippet.json\` | Beispiel-Zuordnung für Masterportal \`config.json\` |
| \`conversion-meta.json\` | Zoom, Zeitstempel, legendWarnings |

Styles liegen in \`../masterportal/\`.
`

const writeLegendBundle = async (
  mpOut: string,
  styles: { styleId: string }[],
  legendStyleIds: readonly string[],
  filename: string,
) => {
  const legendStyles = styles.filter((style) => legendStyleIds.includes(style.styleId))
  const legendBundlePath = path.join(mpOut, filename)
  await writeFile(legendBundlePath, `${JSON.stringify(legendStyles, null, 2)}\n`)
  console.log(`Wrote ${legendBundlePath}`)
}

const main = async () => {
  const { zoom, outDir, splitStyles } = parseArgs()
  const mpOut = path.join(outDir, masterportalDir)
  const tildaOut = path.join(outDir, tildaDir)

  await mkdir(mpOut, { recursive: true })
  await mkdir(tildaOut, { recursive: true })

  const tileResult = buildParkbeschraenkungenStyles({ zoom })
  const gpkgResult = buildParkingPublicGpkgStyles({ zoom })

  const allStyles = [...tileResult.styles, ...gpkgResult.styles]

  if (splitStyles) {
    for (const style of allStyles) {
      const filePath = path.join(mpOut, `${style.styleId}.json`)
      await writeFile(filePath, `${JSON.stringify([style], null, 2)}\n`)
      console.log(`Wrote ${filePath}`)
    }
  }

  const tileBundlePath = path.join(mpOut, 'parkbeschraenkungen.json')
  await writeFile(tileBundlePath, `${JSON.stringify(tileResult.styles, null, 2)}\n`)
  console.log(`Wrote ${tileBundlePath}`)

  const gpkgBundlePath = path.join(mpOut, 'parking_public.gpkg.styles.json')
  await writeFile(gpkgBundlePath, `${JSON.stringify(gpkgResult.styles, null, 2)}\n`)
  console.log(`Wrote ${gpkgBundlePath}`)

  await writeLegendBundle(
    mpOut,
    tileResult.styles,
    LEGEND_STYLE_IDS,
    'parkbeschraenkungen-legend.json',
  )
  await writeLegendBundle(
    mpOut,
    gpkgResult.styles,
    GPKG_LEGEND_STYLE_IDS,
    'parking_public.gpkg.legend.json',
  )

  await writeFile(path.join(mpOut, 'README.md'), masterportalReadme)

  const manifestPath = path.join(tildaOut, 'manifest.json')
  await writeFile(manifestPath, `${JSON.stringify({ layers: tileResult.manifest }, null, 2)}\n`)
  console.log(`Wrote ${manifestPath}`)

  const gpkgManifestPath = path.join(tildaOut, 'gpkg-manifest.json')
  await writeFile(
    gpkgManifestPath,
    `${JSON.stringify({ layers: gpkgResult.gpkgManifest }, null, 2)}\n`,
  )
  console.log(`Wrote ${gpkgManifestPath}`)

  const snippetPath = path.join(tildaOut, 'masterportal-layer-snippet.json')
  await writeFile(
    snippetPath,
    `${JSON.stringify({ layers: gpkgResult.masterportalLayerSnippet }, null, 2)}\n`,
  )
  console.log(`Wrote ${snippetPath}`)

  const legendWarnings = [...tileResult.legendWarnings, ...gpkgResult.legendWarnings]
  const uniqueWarnings = [...new Set(legendWarnings)]

  const metaPath = path.join(tildaOut, 'conversion-meta.json')
  await writeFile(
    metaPath,
    `${JSON.stringify({ zoom, generatedAt: new Date().toISOString(), legendWarnings: uniqueWarnings }, null, 2)}\n`,
  )
  console.log(`Wrote ${metaPath}`)

  if (uniqueWarnings.length > 0) {
    console.warn('Legend warnings:')
    for (const warning of uniqueWarnings) {
      console.warn(`  - ${warning}`)
    }
  }

  await writeFile(path.join(tildaOut, 'README.md'), tildaReadme)

  const staleRootFiles = (await readdir(outDir)).filter(
    (name) => name.endsWith('.json') && !name.startsWith('.'),
  )
  for (const name of staleRootFiles) {
    await unlink(path.join(outDir, name))
    console.log(`Removed stale ${path.join(outDir, name)}`)
  }
}

await main()
