/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegionenRouteImport } from './routes/regionen'
import { Route as PreviewRouteImport } from './routes/preview'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as PagesRouteImport } from './routes/_pages'
import { Route as HomeRouteImport } from './routes/_home'
import { Route as RegionenIndexRouteImport } from './routes/regionen/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as HomeIndexRouteImport } from './routes/_home/index'
import { Route as RegionenStatsRouteImport } from './routes/regionen/stats'
import { Route as RegionenRegionSlugRouteImport } from './routes/regionen/$regionSlug'
import { Route as PreviewRootFallbackRouteImport } from './routes/preview/root-fallback'
import { Route as PreviewRegionPendingRouteImport } from './routes/preview/region-pending'
import { Route as PreviewRegionErrorRouteImport } from './routes/preview/region-error'
import { Route as PreviewNotFoundRouteImport } from './routes/preview/not-found'
import { Route as PreviewDefaultPendingRouteImport } from './routes/preview/default-pending'
import { Route as PreviewDefaultErrorRouteImport } from './routes/preview/default-error'
import { Route as ApiUploadsRouteImport } from './routes/api/uploads'
import { Route as ApiStatsRouteImport } from './routes/api/stats'
import { Route as ApiRegionsRouteImport } from './routes/api/regions'
import { Route as ApiProcessingDatesMapillaryRouteImport } from './routes/api/processing-dates-mapillary'
import { Route as ApiProcessingDatesRouteImport } from './routes/api/processing-dates'
import { Route as ApiMapStyleRouteImport } from './routes/api/map-style'
import { Route as ApiCampaignsRouteImport } from './routes/api/campaigns'
import { Route as ApiBoundaryRouteImport } from './routes/api/boundary'
import { Route as AdminUploadsRouteImport } from './routes/admin/uploads'
import { Route as AdminStaticDatasetCategoriesRouteImport } from './routes/admin/static-dataset-categories'
import { Route as AdminRegionsRouteImport } from './routes/admin/regions'
import { Route as AdminQaConfigsRouteImport } from './routes/admin/qa-configs'
import { Route as AdminMembershipsRouteImport } from './routes/admin/memberships'
import { Route as PagesOAuthErrorRouteImport } from './routes/_pages/oAuthError'
import { Route as PagesKontaktRouteImport } from './routes/_pages/kontakt'
import { Route as PagesDatenschutzRouteImport } from './routes/_pages/datenschutz'
import { Route as PagesAccessDeniedRouteImport } from './routes/_pages/access-denied'
import { Route as AdminUploadsIndexRouteImport } from './routes/admin/uploads/index'
import { Route as AdminStaticDatasetCategoriesIndexRouteImport } from './routes/admin/static-dataset-categories/index'
import { Route as AdminRegionsIndexRouteImport } from './routes/admin/regions/index'
import { Route as AdminQaConfigsIndexRouteImport } from './routes/admin/qa-configs/index'
import { Route as AdminMembershipsIndexRouteImport } from './routes/admin/memberships/index'
import { Route as ApiUploadsCreateRouteImport } from './routes/api/uploads.create'
import { Route as ApiUploadsSlugRouteImport } from './routes/api/uploads.$slug'
import { Route as ApiSignInOsmRouteImport } from './routes/api/sign-in.osm'
import { Route as ApiPrivateWarmCacheRouteImport } from './routes/api/private/warm-cache'
import { Route as ApiPrivateRegisterSqlFunctionsRouteImport } from './routes/api/private/register-sql-functions'
import { Route as ApiPrivatePostProcessingStatisticsRouteImport } from './routes/api/private/post-processing-statistics'
import { Route as ApiPrivatePostProcessingQaUpdateRouteImport } from './routes/api/private/post-processing-qa-update'
import { Route as ApiPrivatePostProcessingHookRouteImport } from './routes/api/private/post-processing-hook'
import { Route as ApiPrivateGenerateMaprouletteTasksRouteImport } from './routes/api/private/generate-maproulette-tasks'
import { Route as ApiOsmNotesRssRouteImport } from './routes/api/osm-notes.rss'
import { Route as ApiNotesRegionSlugRouteImport } from './routes/api/notes.$regionSlug'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth.$'
import { Route as AdminUploadsSlugRouteImport } from './routes/admin/uploads.$slug'
import { Route as AdminStaticDatasetCategoriesNewRouteImport } from './routes/admin/static-dataset-categories/new'
import { Route as AdminStaticDatasetCategoriesCategoryKeyRouteImport } from './routes/admin/static-dataset-categories/$categoryKey'
import { Route as AdminRegionsNewRouteImport } from './routes/admin/regions.new'
import { Route as AdminQaConfigsNewRouteImport } from './routes/admin/qa-configs.new'
import { Route as AdminMembershipsNewRouteImport } from './routes/admin/memberships.new'
import { Route as PagesSettingsUserRouteImport } from './routes/_pages/settings.user'
import { Route as PagesDocsMapillaryCoverageRouteImport } from './routes/_pages/docs.mapillary-coverage'
import { Route as PagesDocsTableNameRouteImport } from './routes/_pages/docs.$tableName'
import { Route as ApiRegionsRegionSlugUploadsCsvRouteImport } from './routes/api/regions.$regionSlug.uploads-csv'
import { Route as ApiNotesRegionSlugDownloadRouteImport } from './routes/api/notes.$regionSlug.download'
import { Route as ApiMaprouletteStatisticProxyChallengeIdRouteImport } from './routes/api/maproulette.statistic-proxy.$challengeId'
import { Route as ApiMaprouletteDataTest_tag_fix_twoRouteImport } from './routes/api/maproulette.data.test_tag_fix_two'
import { Route as ApiMaprouletteDataTest_tag_fix_cyclewaySharedRouteImport } from './routes/api/maproulette.data.test_tag_fix_cycleway-shared'
import { Route as ApiMaprouletteDataTest_tag_fixRouteImport } from './routes/api/maproulette.data.test_tag_fix'
import { Route as ApiMaprouletteDataProjectKeyRouteImport } from './routes/api/maproulette.data.$projectKey'
import { Route as ApiExportRegionSlugTableNameRouteImport } from './routes/api/export.$regionSlug.$tableName'
import { Route as ApiExportOgrRegionSlugTableNameRouteImport } from './routes/api/export-ogr.$regionSlug.$tableName'
import { Route as AdminRegionsRegionSlugEditRouteImport } from './routes/admin/regions.$regionSlug.edit'
import { Route as AdminQaConfigsIdEditRouteImport } from './routes/admin/qa-configs.$id.edit'
import { Route as ApiAdminQaConfigsIdExportCsvRouteImport } from './routes/api/admin.qa-configs.$id.export-csv'

const RegionenRoute = RegionenRouteImport.update({
  id: '/regionen',
  path: '/regionen',
  getParentRoute: () => rootRouteImport,
} as any)
const PreviewRoute = PreviewRouteImport.update({
  id: '/preview',
  path: '/preview',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const PagesRoute = PagesRouteImport.update({
  id: '/_pages',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/_home',
  getParentRoute: () => rootRouteImport,
} as any)
const RegionenIndexRoute = RegionenIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => RegionenRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const HomeIndexRoute = HomeIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => HomeRoute,
} as any)
const RegionenStatsRoute = RegionenStatsRouteImport.update({
  id: '/stats',
  path: '/stats',
  getParentRoute: () => RegionenRoute,
} as any)
const RegionenRegionSlugRoute = RegionenRegionSlugRouteImport.update({
  id: '/$regionSlug',
  path: '/$regionSlug',
  getParentRoute: () => RegionenRoute,
} as any)
const PreviewRootFallbackRoute = PreviewRootFallbackRouteImport.update({
  id: '/root-fallback',
  path: '/root-fallback',
  getParentRoute: () => PreviewRoute,
} as any)
const PreviewRegionPendingRoute = PreviewRegionPendingRouteImport.update({
  id: '/region-pending',
  path: '/region-pending',
  getParentRoute: () => PreviewRoute,
} as any)
const PreviewRegionErrorRoute = PreviewRegionErrorRouteImport.update({
  id: '/region-error',
  path: '/region-error',
  getParentRoute: () => PreviewRoute,
} as any)
const PreviewNotFoundRoute = PreviewNotFoundRouteImport.update({
  id: '/not-found',
  path: '/not-found',
  getParentRoute: () => PreviewRoute,
} as any)
const PreviewDefaultPendingRoute = PreviewDefaultPendingRouteImport.update({
  id: '/default-pending',
  path: '/default-pending',
  getParentRoute: () => PreviewRoute,
} as any)
const PreviewDefaultErrorRoute = PreviewDefaultErrorRouteImport.update({
  id: '/default-error',
  path: '/default-error',
  getParentRoute: () => PreviewRoute,
} as any)
const ApiUploadsRoute = ApiUploadsRouteImport.update({
  id: '/api/uploads',
  path: '/api/uploads',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStatsRoute = ApiStatsRouteImport.update({
  id: '/api/stats',
  path: '/api/stats',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRegionsRoute = ApiRegionsRouteImport.update({
  id: '/api/regions',
  path: '/api/regions',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProcessingDatesMapillaryRoute =
  ApiProcessingDatesMapillaryRouteImport.update({
    id: '/api/processing-dates-mapillary',
    path: '/api/processing-dates-mapillary',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiProcessingDatesRoute = ApiProcessingDatesRouteImport.update({
  id: '/api/processing-dates',
  path: '/api/processing-dates',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMapStyleRoute = ApiMapStyleRouteImport.update({
  id: '/api/map-style',
  path: '/api/map-style',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCampaignsRoute = ApiCampaignsRouteImport.update({
  id: '/api/campaigns',
  path: '/api/campaigns',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBoundaryRoute = ApiBoundaryRouteImport.update({
  id: '/api/boundary',
  path: '/api/boundary',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUploadsRoute = AdminUploadsRouteImport.update({
  id: '/uploads',
  path: '/uploads',
  getParentRoute: () => AdminRoute,
} as any)
const AdminStaticDatasetCategoriesRoute =
  AdminStaticDatasetCategoriesRouteImport.update({
    id: '/static-dataset-categories',
    path: '/static-dataset-categories',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminRegionsRoute = AdminRegionsRouteImport.update({
  id: '/regions',
  path: '/regions',
  getParentRoute: () => AdminRoute,
} as any)
const AdminQaConfigsRoute = AdminQaConfigsRouteImport.update({
  id: '/qa-configs',
  path: '/qa-configs',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMembershipsRoute = AdminMembershipsRouteImport.update({
  id: '/memberships',
  path: '/memberships',
  getParentRoute: () => AdminRoute,
} as any)
const PagesOAuthErrorRoute = PagesOAuthErrorRouteImport.update({
  id: '/oAuthError',
  path: '/oAuthError',
  getParentRoute: () => PagesRoute,
} as any)
const PagesKontaktRoute = PagesKontaktRouteImport.update({
  id: '/kontakt',
  path: '/kontakt',
  getParentRoute: () => PagesRoute,
} as any)
const PagesDatenschutzRoute = PagesDatenschutzRouteImport.update({
  id: '/datenschutz',
  path: '/datenschutz',
  getParentRoute: () => PagesRoute,
} as any)
const PagesAccessDeniedRoute = PagesAccessDeniedRouteImport.update({
  id: '/access-denied',
  path: '/access-denied',
  getParentRoute: () => PagesRoute,
} as any)
const AdminUploadsIndexRoute = AdminUploadsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminUploadsRoute,
} as any)
const AdminStaticDatasetCategoriesIndexRoute =
  AdminStaticDatasetCategoriesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AdminStaticDatasetCategoriesRoute,
  } as any)
const AdminRegionsIndexRoute = AdminRegionsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRegionsRoute,
} as any)
const AdminQaConfigsIndexRoute = AdminQaConfigsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminQaConfigsRoute,
} as any)
const AdminMembershipsIndexRoute = AdminMembershipsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminMembershipsRoute,
} as any)
const ApiUploadsCreateRoute = ApiUploadsCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => ApiUploadsRoute,
} as any)
const ApiUploadsSlugRoute = ApiUploadsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ApiUploadsRoute,
} as any)
const ApiSignInOsmRoute = ApiSignInOsmRouteImport.update({
  id: '/api/sign-in/osm',
  path: '/api/sign-in/osm',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPrivateWarmCacheRoute = ApiPrivateWarmCacheRouteImport.update({
  id: '/api/private/warm-cache',
  path: '/api/private/warm-cache',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPrivateRegisterSqlFunctionsRoute =
  ApiPrivateRegisterSqlFunctionsRouteImport.update({
    id: '/api/private/register-sql-functions',
    path: '/api/private/register-sql-functions',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPrivatePostProcessingStatisticsRoute =
  ApiPrivatePostProcessingStatisticsRouteImport.update({
    id: '/api/private/post-processing-statistics',
    path: '/api/private/post-processing-statistics',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPrivatePostProcessingQaUpdateRoute =
  ApiPrivatePostProcessingQaUpdateRouteImport.update({
    id: '/api/private/post-processing-qa-update',
    path: '/api/private/post-processing-qa-update',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPrivatePostProcessingHookRoute =
  ApiPrivatePostProcessingHookRouteImport.update({
    id: '/api/private/post-processing-hook',
    path: '/api/private/post-processing-hook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPrivateGenerateMaprouletteTasksRoute =
  ApiPrivateGenerateMaprouletteTasksRouteImport.update({
    id: '/api/private/generate-maproulette-tasks',
    path: '/api/private/generate-maproulette-tasks',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiOsmNotesRssRoute = ApiOsmNotesRssRouteImport.update({
  id: '/api/osm-notes/rss',
  path: '/api/osm-notes/rss',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiNotesRegionSlugRoute = ApiNotesRegionSlugRouteImport.update({
  id: '/api/notes/$regionSlug',
  path: '/api/notes/$regionSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUploadsSlugRoute = AdminUploadsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => AdminUploadsRoute,
} as any)
const AdminStaticDatasetCategoriesNewRoute =
  AdminStaticDatasetCategoriesNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => AdminStaticDatasetCategoriesRoute,
  } as any)
const AdminStaticDatasetCategoriesCategoryKeyRoute =
  AdminStaticDatasetCategoriesCategoryKeyRouteImport.update({
    id: '/$categoryKey',
    path: '/$categoryKey',
    getParentRoute: () => AdminStaticDatasetCategoriesRoute,
  } as any)
const AdminRegionsNewRoute = AdminRegionsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AdminRegionsRoute,
} as any)
const AdminQaConfigsNewRoute = AdminQaConfigsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AdminQaConfigsRoute,
} as any)
const AdminMembershipsNewRoute = AdminMembershipsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AdminMembershipsRoute,
} as any)
const PagesSettingsUserRoute = PagesSettingsUserRouteImport.update({
  id: '/settings/user',
  path: '/settings/user',
  getParentRoute: () => PagesRoute,
} as any)
const PagesDocsMapillaryCoverageRoute =
  PagesDocsMapillaryCoverageRouteImport.update({
    id: '/docs/mapillary-coverage',
    path: '/docs/mapillary-coverage',
    getParentRoute: () => PagesRoute,
  } as any)
const PagesDocsTableNameRoute = PagesDocsTableNameRouteImport.update({
  id: '/docs/$tableName',
  path: '/docs/$tableName',
  getParentRoute: () => PagesRoute,
} as any)
const ApiRegionsRegionSlugUploadsCsvRoute =
  ApiRegionsRegionSlugUploadsCsvRouteImport.update({
    id: '/$regionSlug/uploads-csv',
    path: '/$regionSlug/uploads-csv',
    getParentRoute: () => ApiRegionsRoute,
  } as any)
const ApiNotesRegionSlugDownloadRoute =
  ApiNotesRegionSlugDownloadRouteImport.update({
    id: '/download',
    path: '/download',
    getParentRoute: () => ApiNotesRegionSlugRoute,
  } as any)
const ApiMaprouletteStatisticProxyChallengeIdRoute =
  ApiMaprouletteStatisticProxyChallengeIdRouteImport.update({
    id: '/api/maproulette/statistic-proxy/$challengeId',
    path: '/api/maproulette/statistic-proxy/$challengeId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiMaprouletteDataTest_tag_fix_twoRoute =
  ApiMaprouletteDataTest_tag_fix_twoRouteImport.update({
    id: '/api/maproulette/data/test_tag_fix_two',
    path: '/api/maproulette/data/test_tag_fix_two',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiMaprouletteDataTest_tag_fix_cyclewaySharedRoute =
  ApiMaprouletteDataTest_tag_fix_cyclewaySharedRouteImport.update({
    id: '/api/maproulette/data/test_tag_fix_cycleway-shared',
    path: '/api/maproulette/data/test_tag_fix_cycleway-shared',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiMaprouletteDataTest_tag_fixRoute =
  ApiMaprouletteDataTest_tag_fixRouteImport.update({
    id: '/api/maproulette/data/test_tag_fix',
    path: '/api/maproulette/data/test_tag_fix',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiMaprouletteDataProjectKeyRoute =
  ApiMaprouletteDataProjectKeyRouteImport.update({
    id: '/api/maproulette/data/$projectKey',
    path: '/api/maproulette/data/$projectKey',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiExportRegionSlugTableNameRoute =
  ApiExportRegionSlugTableNameRouteImport.update({
    id: '/api/export/$regionSlug/$tableName',
    path: '/api/export/$regionSlug/$tableName',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiExportOgrRegionSlugTableNameRoute =
  ApiExportOgrRegionSlugTableNameRouteImport.update({
    id: '/api/export-ogr/$regionSlug/$tableName',
    path: '/api/export-ogr/$regionSlug/$tableName',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminRegionsRegionSlugEditRoute =
  AdminRegionsRegionSlugEditRouteImport.update({
    id: '/$regionSlug/edit',
    path: '/$regionSlug/edit',
    getParentRoute: () => AdminRegionsRoute,
  } as any)
const AdminQaConfigsIdEditRoute = AdminQaConfigsIdEditRouteImport.update({
  id: '/$id/edit',
  path: '/$id/edit',
  getParentRoute: () => AdminQaConfigsRoute,
} as any)
const ApiAdminQaConfigsIdExportCsvRoute =
  ApiAdminQaConfigsIdExportCsvRouteImport.update({
    id: '/api/admin/qa-configs/$id/export-csv',
    path: '/api/admin/qa-configs/$id/export-csv',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof HomeIndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/preview': typeof PreviewRouteWithChildren
  '/regionen': typeof RegionenRouteWithChildren
  '/access-denied': typeof PagesAccessDeniedRoute
  '/datenschutz': typeof PagesDatenschutzRoute
  '/kontakt': typeof PagesKontaktRoute
  '/oAuthError': typeof PagesOAuthErrorRoute
  '/admin/memberships': typeof AdminMembershipsRouteWithChildren
  '/admin/qa-configs': typeof AdminQaConfigsRouteWithChildren
  '/admin/regions': typeof AdminRegionsRouteWithChildren
  '/admin/static-dataset-categories': typeof AdminStaticDatasetCategoriesRouteWithChildren
  '/admin/uploads': typeof AdminUploadsRouteWithChildren
  '/api/boundary': typeof ApiBoundaryRoute
  '/api/campaigns': typeof ApiCampaignsRoute
  '/api/map-style': typeof ApiMapStyleRoute
  '/api/processing-dates': typeof ApiProcessingDatesRoute
  '/api/processing-dates-mapillary': typeof ApiProcessingDatesMapillaryRoute
  '/api/regions': typeof ApiRegionsRouteWithChildren
  '/api/stats': typeof ApiStatsRoute
  '/api/uploads': typeof ApiUploadsRouteWithChildren
  '/preview/default-error': typeof PreviewDefaultErrorRoute
  '/preview/default-pending': typeof PreviewDefaultPendingRoute
  '/preview/not-found': typeof PreviewNotFoundRoute
  '/preview/region-error': typeof PreviewRegionErrorRoute
  '/preview/region-pending': typeof PreviewRegionPendingRoute
  '/preview/root-fallback': typeof PreviewRootFallbackRoute
  '/regionen/$regionSlug': typeof RegionenRegionSlugRoute
  '/regionen/stats': typeof RegionenStatsRoute
  '/admin/': typeof AdminIndexRoute
  '/regionen/': typeof RegionenIndexRoute
  '/docs/$tableName': typeof PagesDocsTableNameRoute
  '/docs/mapillary-coverage': typeof PagesDocsMapillaryCoverageRoute
  '/settings/user': typeof PagesSettingsUserRoute
  '/admin/memberships/new': typeof AdminMembershipsNewRoute
  '/admin/qa-configs/new': typeof AdminQaConfigsNewRoute
  '/admin/regions/new': typeof AdminRegionsNewRoute
  '/admin/static-dataset-categories/$categoryKey': typeof AdminStaticDatasetCategoriesCategoryKeyRoute
  '/admin/static-dataset-categories/new': typeof AdminStaticDatasetCategoriesNewRoute
  '/admin/uploads/$slug': typeof AdminUploadsSlugRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/notes/$regionSlug': typeof ApiNotesRegionSlugRouteWithChildren
  '/api/osm-notes/rss': typeof ApiOsmNotesRssRoute
  '/api/private/generate-maproulette-tasks': typeof ApiPrivateGenerateMaprouletteTasksRoute
  '/api/private/post-processing-hook': typeof ApiPrivatePostProcessingHookRoute
  '/api/private/post-processing-qa-update': typeof ApiPrivatePostProcessingQaUpdateRoute
  '/api/private/post-processing-statistics': typeof ApiPrivatePostProcessingStatisticsRoute
  '/api/private/register-sql-functions': typeof ApiPrivateRegisterSqlFunctionsRoute
  '/api/private/warm-cache': typeof ApiPrivateWarmCacheRoute
  '/api/sign-in/osm': typeof ApiSignInOsmRoute
  '/api/uploads/$slug': typeof ApiUploadsSlugRoute
  '/api/uploads/create': typeof ApiUploadsCreateRoute
  '/admin/memberships/': typeof AdminMembershipsIndexRoute
  '/admin/qa-configs/': typeof AdminQaConfigsIndexRoute
  '/admin/regions/': typeof AdminRegionsIndexRoute
  '/admin/static-dataset-categories/': typeof AdminStaticDatasetCategoriesIndexRoute
  '/admin/uploads/': typeof AdminUploadsIndexRoute
  '/admin/qa-configs/$id/edit': typeof AdminQaConfigsIdEditRoute
  '/admin/regions/$regionSlug/edit': typeof AdminRegionsRegionSlugEditRoute
  '/api/export-ogr/$regionSlug/$tableName': typeof ApiExportOgrRegionSlugTableNameRoute
  '/api/export/$regionSlug/$tableName': typeof ApiExportRegionSlugTableNameRoute
  '/api/maproulette/data/$projectKey': typeof ApiMaprouletteDataProjectKeyRoute
  '/api/maproulette/data/test_tag_fix': typeof ApiMaprouletteDataTest_tag_fixRoute
  '/api/maproulette/data/test_tag_fix_cycleway-shared': typeof ApiMaprouletteDataTest_tag_fix_cyclewaySharedRoute
  '/api/maproulette/data/test_tag_fix_two': typeof ApiMaprouletteDataTest_tag_fix_twoRoute
  '/api/maproulette/statistic-proxy/$challengeId': typeof ApiMaprouletteStatisticProxyChallengeIdRoute
  '/api/notes/$regionSlug/download': typeof ApiNotesRegionSlugDownloadRoute
  '/api/regions/$regionSlug/uploads-csv': typeof ApiRegionsRegionSlugUploadsCsvRoute
  '/api/admin/qa-configs/$id/export-csv': typeof ApiAdminQaConfigsIdExportCsvRoute
}
export interface FileRoutesByTo {
  '/': typeof HomeIndexRoute
  '/preview': typeof PreviewRouteWithChildren
  '/access-denied': typeof PagesAccessDeniedRoute
  '/datenschutz': typeof PagesDatenschutzRoute
  '/kontakt': typeof PagesKontaktRoute
  '/oAuthError': typeof PagesOAuthErrorRoute
  '/api/boundary': typeof ApiBoundaryRoute
  '/api/campaigns': typeof ApiCampaignsRoute
  '/api/map-style': typeof ApiMapStyleRoute
  '/api/processing-dates': typeof ApiProcessingDatesRoute
  '/api/processing-dates-mapillary': typeof ApiProcessingDatesMapillaryRoute
  '/api/regions': typeof ApiRegionsRouteWithChildren
  '/api/stats': typeof ApiStatsRoute
  '/api/uploads': typeof ApiUploadsRouteWithChildren
  '/preview/default-error': typeof PreviewDefaultErrorRoute
  '/preview/default-pending': typeof PreviewDefaultPendingRoute
  '/preview/not-found': typeof PreviewNotFoundRoute
  '/preview/region-error': typeof PreviewRegionErrorRoute
  '/preview/region-pending': typeof PreviewRegionPendingRoute
  '/preview/root-fallback': typeof PreviewRootFallbackRoute
  '/regionen/$regionSlug': typeof RegionenRegionSlugRoute
  '/regionen/stats': typeof RegionenStatsRoute
  '/admin': typeof AdminIndexRoute
  '/regionen': typeof RegionenIndexRoute
  '/docs/$tableName': typeof PagesDocsTableNameRoute
  '/docs/mapillary-coverage': typeof PagesDocsMapillaryCoverageRoute
  '/settings/user': typeof PagesSettingsUserRoute
  '/admin/memberships/new': typeof AdminMembershipsNewRoute
  '/admin/qa-configs/new': typeof AdminQaConfigsNewRoute
  '/admin/regions/new': typeof AdminRegionsNewRoute
  '/admin/static-dataset-categories/$categoryKey': typeof AdminStaticDatasetCategoriesCategoryKeyRoute
  '/admin/static-dataset-categories/new': typeof AdminStaticDatasetCategoriesNewRoute
  '/admin/uploads/$slug': typeof AdminUploadsSlugRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/notes/$regionSlug': typeof ApiNotesRegionSlugRouteWithChildren
  '/api/osm-notes/rss': typeof ApiOsmNotesRssRoute
  '/api/private/generate-maproulette-tasks': typeof ApiPrivateGenerateMaprouletteTasksRoute
  '/api/private/post-processing-hook': typeof ApiPrivatePostProcessingHookRoute
  '/api/private/post-processing-qa-update': typeof ApiPrivatePostProcessingQaUpdateRoute
  '/api/private/post-processing-statistics': typeof ApiPrivatePostProcessingStatisticsRoute
  '/api/private/register-sql-functions': typeof ApiPrivateRegisterSqlFunctionsRoute
  '/api/private/warm-cache': typeof ApiPrivateWarmCacheRoute
  '/api/sign-in/osm': typeof ApiSignInOsmRoute
  '/api/uploads/$slug': typeof ApiUploadsSlugRoute
  '/api/uploads/create': typeof ApiUploadsCreateRoute
  '/admin/memberships': typeof AdminMembershipsIndexRoute
  '/admin/qa-configs': typeof AdminQaConfigsIndexRoute
  '/admin/regions': typeof AdminRegionsIndexRoute
  '/admin/static-dataset-categories': typeof AdminStaticDatasetCategoriesIndexRoute
  '/admin/uploads': typeof AdminUploadsIndexRoute
  '/admin/qa-configs/$id/edit': typeof AdminQaConfigsIdEditRoute
  '/admin/regions/$regionSlug/edit': typeof AdminRegionsRegionSlugEditRoute
  '/api/export-ogr/$regionSlug/$tableName': typeof ApiExportOgrRegionSlugTableNameRoute
  '/api/export/$regionSlug/$tableName': typeof ApiExportRegionSlugTableNameRoute
  '/api/maproulette/data/$projectKey': typeof ApiMaprouletteDataProjectKeyRoute
  '/api/maproulette/data/test_tag_fix': typeof ApiMaprouletteDataTest_tag_fixRoute
  '/api/maproulette/data/test_tag_fix_cycleway-shared': typeof ApiMaprouletteDataTest_tag_fix_cyclewaySharedRoute
  '/api/maproulette/data/test_tag_fix_two': typeof ApiMaprouletteDataTest_tag_fix_twoRoute
  '/api/maproulette/statistic-proxy/$challengeId': typeof ApiMaprouletteStatisticProxyChallengeIdRoute
  '/api/notes/$regionSlug/download': typeof ApiNotesRegionSlugDownloadRoute
  '/api/regions/$regionSlug/uploads-csv': typeof ApiRegionsRegionSlugUploadsCsvRoute
  '/api/admin/qa-configs/$id/export-csv': typeof ApiAdminQaConfigsIdExportCsvRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_home': typeof HomeRouteWithChildren
  '/_pages': typeof PagesRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/preview': typeof PreviewRouteWithChildren
  '/regionen': typeof RegionenRouteWithChildren
  '/_pages/access-denied': typeof PagesAccessDeniedRoute
  '/_pages/datenschutz': typeof PagesDatenschutzRoute
  '/_pages/kontakt': typeof PagesKontaktRoute
  '/_pages/oAuthError': typeof PagesOAuthErrorRoute
  '/admin/memberships': typeof AdminMembershipsRouteWithChildren
  '/admin/qa-configs': typeof AdminQaConfigsRouteWithChildren
  '/admin/regions': typeof AdminRegionsRouteWithChildren
  '/admin/static-dataset-categories': typeof AdminStaticDatasetCategoriesRouteWithChildren
  '/admin/uploads': typeof AdminUploadsRouteWithChildren
  '/api/boundary': typeof ApiBoundaryRoute
  '/api/campaigns': typeof ApiCampaignsRoute
  '/api/map-style': typeof ApiMapStyleRoute
  '/api/processing-dates': typeof ApiProcessingDatesRoute
  '/api/processing-dates-mapillary': typeof ApiProcessingDatesMapillaryRoute
  '/api/regions': typeof ApiRegionsRouteWithChildren
  '/api/stats': typeof ApiStatsRoute
  '/api/uploads': typeof ApiUploadsRouteWithChildren
  '/preview/default-error': typeof PreviewDefaultErrorRoute
  '/preview/default-pending': typeof PreviewDefaultPendingRoute
  '/preview/not-found': typeof PreviewNotFoundRoute
  '/preview/region-error': typeof PreviewRegionErrorRoute
  '/preview/region-pending': typeof PreviewRegionPendingRoute
  '/preview/root-fallback': typeof PreviewRootFallbackRoute
  '/regionen/$regionSlug': typeof RegionenRegionSlugRoute
  '/regionen/stats': typeof RegionenStatsRoute
  '/_home/': typeof HomeIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/regionen/': typeof RegionenIndexRoute
  '/_pages/docs/$tableName': typeof PagesDocsTableNameRoute
  '/_pages/docs/mapillary-coverage': typeof PagesDocsMapillaryCoverageRoute
  '/_pages/settings/user': typeof PagesSettingsUserRoute
  '/admin/memberships/new': typeof AdminMembershipsNewRoute
  '/admin/qa-configs/new': typeof AdminQaConfigsNewRoute
  '/admin/regions/new': typeof AdminRegionsNewRoute
  '/admin/static-dataset-categories/$categoryKey': typeof AdminStaticDatasetCategoriesCategoryKeyRoute
  '/admin/static-dataset-categories/new': typeof AdminStaticDatasetCategoriesNewRoute
  '/admin/uploads/$slug': typeof AdminUploadsSlugRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/notes/$regionSlug': typeof ApiNotesRegionSlugRouteWithChildren
  '/api/osm-notes/rss': typeof ApiOsmNotesRssRoute
  '/api/private/generate-maproulette-tasks': typeof ApiPrivateGenerateMaprouletteTasksRoute
  '/api/private/post-processing-hook': typeof ApiPrivatePostProcessingHookRoute
  '/api/private/post-processing-qa-update': typeof ApiPrivatePostProcessingQaUpdateRoute
  '/api/private/post-processing-statistics': typeof ApiPrivatePostProcessingStatisticsRoute
  '/api/private/register-sql-functions': typeof ApiPrivateRegisterSqlFunctionsRoute
  '/api/private/warm-cache': typeof ApiPrivateWarmCacheRoute
  '/api/sign-in/osm': typeof ApiSignInOsmRoute
  '/api/uploads/$slug': typeof ApiUploadsSlugRoute
  '/api/uploads/create': typeof ApiUploadsCreateRoute
  '/admin/memberships/': typeof AdminMembershipsIndexRoute
  '/admin/qa-configs/': typeof AdminQaConfigsIndexRoute
  '/admin/regions/': typeof AdminRegionsIndexRoute
  '/admin/static-dataset-categories/': typeof AdminStaticDatasetCategoriesIndexRoute
  '/admin/uploads/': typeof AdminUploadsIndexRoute
  '/admin/qa-configs/$id/edit': typeof AdminQaConfigsIdEditRoute
  '/admin/regions/$regionSlug/edit': typeof AdminRegionsRegionSlugEditRoute
  '/api/export-ogr/$regionSlug/$tableName': typeof ApiExportOgrRegionSlugTableNameRoute
  '/api/export/$regionSlug/$tableName': typeof ApiExportRegionSlugTableNameRoute
  '/api/maproulette/data/$projectKey': typeof ApiMaprouletteDataProjectKeyRoute
  '/api/maproulette/data/test_tag_fix': typeof ApiMaprouletteDataTest_tag_fixRoute
  '/api/maproulette/data/test_tag_fix_cycleway-shared': typeof ApiMaprouletteDataTest_tag_fix_cyclewaySharedRoute
  '/api/maproulette/data/test_tag_fix_two': typeof ApiMaprouletteDataTest_tag_fix_twoRoute
  '/api/maproulette/statistic-proxy/$challengeId': typeof ApiMaprouletteStatisticProxyChallengeIdRoute
  '/api/notes/$regionSlug/download': typeof ApiNotesRegionSlugDownloadRoute
  '/api/regions/$regionSlug/uploads-csv': typeof ApiRegionsRegionSlugUploadsCsvRoute
  '/api/admin/qa-configs/$id/export-csv': typeof ApiAdminQaConfigsIdExportCsvRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/preview'
    | '/regionen'
    | '/access-denied'
    | '/datenschutz'
    | '/kontakt'
    | '/oAuthError'
    | '/admin/memberships'
    | '/admin/qa-configs'
    | '/admin/regions'
    | '/admin/static-dataset-categories'
    | '/admin/uploads'
    | '/api/boundary'
    | '/api/campaigns'
    | '/api/map-style'
    | '/api/processing-dates'
    | '/api/processing-dates-mapillary'
    | '/api/regions'
    | '/api/stats'
    | '/api/uploads'
    | '/preview/default-error'
    | '/preview/default-pending'
    | '/preview/not-found'
    | '/preview/region-error'
    | '/preview/region-pending'
    | '/preview/root-fallback'
    | '/regionen/$regionSlug'
    | '/regionen/stats'
    | '/admin/'
    | '/regionen/'
    | '/docs/$tableName'
    | '/docs/mapillary-coverage'
    | '/settings/user'
    | '/admin/memberships/new'
    | '/admin/qa-configs/new'
    | '/admin/regions/new'
    | '/admin/static-dataset-categories/$categoryKey'
    | '/admin/static-dataset-categories/new'
    | '/admin/uploads/$slug'
    | '/api/auth/$'
    | '/api/notes/$regionSlug'
    | '/api/osm-notes/rss'
    | '/api/private/generate-maproulette-tasks'
    | '/api/private/post-processing-hook'
    | '/api/private/post-processing-qa-update'
    | '/api/private/post-processing-statistics'
    | '/api/private/register-sql-functions'
    | '/api/private/warm-cache'
    | '/api/sign-in/osm'
    | '/api/uploads/$slug'
    | '/api/uploads/create'
    | '/admin/memberships/'
    | '/admin/qa-configs/'
    | '/admin/regions/'
    | '/admin/static-dataset-categories/'
    | '/admin/uploads/'
    | '/admin/qa-configs/$id/edit'
    | '/admin/regions/$regionSlug/edit'
    | '/api/export-ogr/$regionSlug/$tableName'
    | '/api/export/$regionSlug/$tableName'
    | '/api/maproulette/data/$projectKey'
    | '/api/maproulette/data/test_tag_fix'
    | '/api/maproulette/data/test_tag_fix_cycleway-shared'
    | '/api/maproulette/data/test_tag_fix_two'
    | '/api/maproulette/statistic-proxy/$challengeId'
    | '/api/notes/$regionSlug/download'
    | '/api/regions/$regionSlug/uploads-csv'
    | '/api/admin/qa-configs/$id/export-csv'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/preview'
    | '/access-denied'
    | '/datenschutz'
    | '/kontakt'
    | '/oAuthError'
    | '/api/boundary'
    | '/api/campaigns'
    | '/api/map-style'
    | '/api/processing-dates'
    | '/api/processing-dates-mapillary'
    | '/api/regions'
    | '/api/stats'
    | '/api/uploads'
    | '/preview/default-error'
    | '/preview/default-pending'
    | '/preview/not-found'
    | '/preview/region-error'
    | '/preview/region-pending'
    | '/preview/root-fallback'
    | '/regionen/$regionSlug'
    | '/regionen/stats'
    | '/admin'
    | '/regionen'
    | '/docs/$tableName'
    | '/docs/mapillary-coverage'
    | '/settings/user'
    | '/admin/memberships/new'
    | '/admin/qa-configs/new'
    | '/admin/regions/new'
    | '/admin/static-dataset-categories/$categoryKey'
    | '/admin/static-dataset-categories/new'
    | '/admin/uploads/$slug'
    | '/api/auth/$'
    | '/api/notes/$regionSlug'
    | '/api/osm-notes/rss'
    | '/api/private/generate-maproulette-tasks'
    | '/api/private/post-processing-hook'
    | '/api/private/post-processing-qa-update'
    | '/api/private/post-processing-statistics'
    | '/api/private/register-sql-functions'
    | '/api/private/warm-cache'
    | '/api/sign-in/osm'
    | '/api/uploads/$slug'
    | '/api/uploads/create'
    | '/admin/memberships'
    | '/admin/qa-configs'
    | '/admin/regions'
    | '/admin/static-dataset-categories'
    | '/admin/uploads'
    | '/admin/qa-configs/$id/edit'
    | '/admin/regions/$regionSlug/edit'
    | '/api/export-ogr/$regionSlug/$tableName'
    | '/api/export/$regionSlug/$tableName'
    | '/api/maproulette/data/$projectKey'
    | '/api/maproulette/data/test_tag_fix'
    | '/api/maproulette/data/test_tag_fix_cycleway-shared'
    | '/api/maproulette/data/test_tag_fix_two'
    | '/api/maproulette/statistic-proxy/$challengeId'
    | '/api/notes/$regionSlug/download'
    | '/api/regions/$regionSlug/uploads-csv'
    | '/api/admin/qa-configs/$id/export-csv'
  id:
    | '__root__'
    | '/_home'
    | '/_pages'
    | '/admin'
    | '/preview'
    | '/regionen'
    | '/_pages/access-denied'
    | '/_pages/datenschutz'
    | '/_pages/kontakt'
    | '/_pages/oAuthError'
    | '/admin/memberships'
    | '/admin/qa-configs'
    | '/admin/regions'
    | '/admin/static-dataset-categories'
    | '/admin/uploads'
    | '/api/boundary'
    | '/api/campaigns'
    | '/api/map-style'
    | '/api/processing-dates'
    | '/api/processing-dates-mapillary'
    | '/api/regions'
    | '/api/stats'
    | '/api/uploads'
    | '/preview/default-error'
    | '/preview/default-pending'
    | '/preview/not-found'
    | '/preview/region-error'
    | '/preview/region-pending'
    | '/preview/root-fallback'
    | '/regionen/$regionSlug'
    | '/regionen/stats'
    | '/_home/'
    | '/admin/'
    | '/regionen/'
    | '/_pages/docs/$tableName'
    | '/_pages/docs/mapillary-coverage'
    | '/_pages/settings/user'
    | '/admin/memberships/new'
    | '/admin/qa-configs/new'
    | '/admin/regions/new'
    | '/admin/static-dataset-categories/$categoryKey'
    | '/admin/static-dataset-categories/new'
    | '/admin/uploads/$slug'
    | '/api/auth/$'
    | '/api/notes/$regionSlug'
    | '/api/osm-notes/rss'
    | '/api/private/generate-maproulette-tasks'
    | '/api/private/post-processing-hook'
    | '/api/private/post-processing-qa-update'
    | '/api/private/post-processing-statistics'
    | '/api/private/register-sql-functions'
    | '/api/private/warm-cache'
    | '/api/sign-in/osm'
    | '/api/uploads/$slug'
    | '/api/uploads/create'
    | '/admin/memberships/'
    | '/admin/qa-configs/'
    | '/admin/regions/'
    | '/admin/static-dataset-categories/'
    | '/admin/uploads/'
    | '/admin/qa-configs/$id/edit'
    | '/admin/regions/$regionSlug/edit'
    | '/api/export-ogr/$regionSlug/$tableName'
    | '/api/export/$regionSlug/$tableName'
    | '/api/maproulette/data/$projectKey'
    | '/api/maproulette/data/test_tag_fix'
    | '/api/maproulette/data/test_tag_fix_cycleway-shared'
    | '/api/maproulette/data/test_tag_fix_two'
    | '/api/maproulette/statistic-proxy/$challengeId'
    | '/api/notes/$regionSlug/download'
    | '/api/regions/$regionSlug/uploads-csv'
    | '/api/admin/qa-configs/$id/export-csv'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  HomeRoute: typeof HomeRouteWithChildren
  PagesRoute: typeof PagesRouteWithChildren
  AdminRoute: typeof AdminRouteWithChildren
  PreviewRoute: typeof PreviewRouteWithChildren
  RegionenRoute: typeof RegionenRouteWithChildren
  ApiBoundaryRoute: typeof ApiBoundaryRoute
  ApiCampaignsRoute: typeof ApiCampaignsRoute
  ApiMapStyleRoute: typeof ApiMapStyleRoute
  ApiProcessingDatesRoute: typeof ApiProcessingDatesRoute
  ApiProcessingDatesMapillaryRoute: typeof ApiProcessingDatesMapillaryRoute
  ApiRegionsRoute: typeof ApiRegionsRouteWithChildren
  ApiStatsRoute: typeof ApiStatsRoute
  ApiUploadsRoute: typeof ApiUploadsRouteWithChildren
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiNotesRegionSlugRoute: typeof ApiNotesRegionSlugRouteWithChildren
  ApiOsmNotesRssRoute: typeof ApiOsmNotesRssRoute
  ApiPrivateGenerateMaprouletteTasksRoute: typeof ApiPrivateGenerateMaprouletteTasksRoute
  ApiPrivatePostProcessingHookRoute: typeof ApiPrivatePostProcessingHookRoute
  ApiPrivatePostProcessingQaUpdateRoute: typeof ApiPrivatePostProcessingQaUpdateRoute
  ApiPrivatePostProcessingStatisticsRoute: typeof ApiPrivatePostProcessingStatisticsRoute
  ApiPrivateRegisterSqlFunctionsRoute: typeof ApiPrivateRegisterSqlFunctionsRoute
  ApiPrivateWarmCacheRoute: typeof ApiPrivateWarmCacheRoute
  ApiSignInOsmRoute: typeof ApiSignInOsmRoute
  ApiExportOgrRegionSlugTableNameRoute: typeof ApiExportOgrRegionSlugTableNameRoute
  ApiExportRegionSlugTableNameRoute: typeof ApiExportRegionSlugTableNameRoute
  ApiMaprouletteDataProjectKeyRoute: typeof ApiMaprouletteDataProjectKeyRoute
  ApiMaprouletteDataTest_tag_fixRoute: typeof ApiMaprouletteDataTest_tag_fixRoute
  ApiMaprouletteDataTest_tag_fix_cyclewaySharedRoute: typeof ApiMaprouletteDataTest_tag_fix_cyclewaySharedRoute
  ApiMaprouletteDataTest_tag_fix_twoRoute: typeof ApiMaprouletteDataTest_tag_fix_twoRoute
  ApiMaprouletteStatisticProxyChallengeIdRoute: typeof ApiMaprouletteStatisticProxyChallengeIdRoute
  ApiAdminQaConfigsIdExportCsvRoute: typeof ApiAdminQaConfigsIdExportCsvRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/regionen': {
      id: '/regionen'
      path: '/regionen'
      fullPath: '/regionen'
      preLoaderRoute: typeof RegionenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/preview': {
      id: '/preview'
      path: '/preview'
      fullPath: '/preview'
      preLoaderRoute: typeof PreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_pages': {
      id: '/_pages'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_home': {
      id: '/_home'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/regionen/': {
      id: '/regionen/'
      path: '/'
      fullPath: '/regionen/'
      preLoaderRoute: typeof RegionenIndexRouteImport
      parentRoute: typeof RegionenRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_home/': {
      id: '/_home/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof HomeIndexRouteImport
      parentRoute: typeof HomeRoute
    }
    '/regionen/stats': {
      id: '/regionen/stats'
      path: '/stats'
      fullPath: '/regionen/stats'
      preLoaderRoute: typeof RegionenStatsRouteImport
      parentRoute: typeof RegionenRoute
    }
    '/regionen/$regionSlug': {
      id: '/regionen/$regionSlug'
      path: '/$regionSlug'
      fullPath: '/regionen/$regionSlug'
      preLoaderRoute: typeof RegionenRegionSlugRouteImport
      parentRoute: typeof RegionenRoute
    }
    '/preview/root-fallback': {
      id: '/preview/root-fallback'
      path: '/root-fallback'
      fullPath: '/preview/root-fallback'
      preLoaderRoute: typeof PreviewRootFallbackRouteImport
      parentRoute: typeof PreviewRoute
    }
    '/preview/region-pending': {
      id: '/preview/region-pending'
      path: '/region-pending'
      fullPath: '/preview/region-pending'
      preLoaderRoute: typeof PreviewRegionPendingRouteImport
      parentRoute: typeof PreviewRoute
    }
    '/preview/region-error': {
      id: '/preview/region-error'
      path: '/region-error'
      fullPath: '/preview/region-error'
      preLoaderRoute: typeof PreviewRegionErrorRouteImport
      parentRoute: typeof PreviewRoute
    }
    '/preview/not-found': {
      id: '/preview/not-found'
      path: '/not-found'
      fullPath: '/preview/not-found'
      preLoaderRoute: typeof PreviewNotFoundRouteImport
      parentRoute: typeof PreviewRoute
    }
    '/preview/default-pending': {
      id: '/preview/default-pending'
      path: '/default-pending'
      fullPath: '/preview/default-pending'
      preLoaderRoute: typeof PreviewDefaultPendingRouteImport
      parentRoute: typeof PreviewRoute
    }
    '/preview/default-error': {
      id: '/preview/default-error'
      path: '/default-error'
      fullPath: '/preview/default-error'
      preLoaderRoute: typeof PreviewDefaultErrorRouteImport
      parentRoute: typeof PreviewRoute
    }
    '/api/uploads': {
      id: '/api/uploads'
      path: '/api/uploads'
      fullPath: '/api/uploads'
      preLoaderRoute: typeof ApiUploadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/stats': {
      id: '/api/stats'
      path: '/api/stats'
      fullPath: '/api/stats'
      preLoaderRoute: typeof ApiStatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/regions': {
      id: '/api/regions'
      path: '/api/regions'
      fullPath: '/api/regions'
      preLoaderRoute: typeof ApiRegionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/processing-dates-mapillary': {
      id: '/api/processing-dates-mapillary'
      path: '/api/processing-dates-mapillary'
      fullPath: '/api/processing-dates-mapillary'
      preLoaderRoute: typeof ApiProcessingDatesMapillaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/processing-dates': {
      id: '/api/processing-dates'
      path: '/api/processing-dates'
      fullPath: '/api/processing-dates'
      preLoaderRoute: typeof ApiProcessingDatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/map-style': {
      id: '/api/map-style'
      path: '/api/map-style'
      fullPath: '/api/map-style'
      preLoaderRoute: typeof ApiMapStyleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/campaigns': {
      id: '/api/campaigns'
      path: '/api/campaigns'
      fullPath: '/api/campaigns'
      preLoaderRoute: typeof ApiCampaignsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/boundary': {
      id: '/api/boundary'
      path: '/api/boundary'
      fullPath: '/api/boundary'
      preLoaderRoute: typeof ApiBoundaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/uploads': {
      id: '/admin/uploads'
      path: '/uploads'
      fullPath: '/admin/uploads'
      preLoaderRoute: typeof AdminUploadsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/static-dataset-categories': {
      id: '/admin/static-dataset-categories'
      path: '/static-dataset-categories'
      fullPath: '/admin/static-dataset-categories'
      preLoaderRoute: typeof AdminStaticDatasetCategoriesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/regions': {
      id: '/admin/regions'
      path: '/regions'
      fullPath: '/admin/regions'
      preLoaderRoute: typeof AdminRegionsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/qa-configs': {
      id: '/admin/qa-configs'
      path: '/qa-configs'
      fullPath: '/admin/qa-configs'
      preLoaderRoute: typeof AdminQaConfigsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/memberships': {
      id: '/admin/memberships'
      path: '/memberships'
      fullPath: '/admin/memberships'
      preLoaderRoute: typeof AdminMembershipsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_pages/oAuthError': {
      id: '/_pages/oAuthError'
      path: '/oAuthError'
      fullPath: '/oAuthError'
      preLoaderRoute: typeof PagesOAuthErrorRouteImport
      parentRoute: typeof PagesRoute
    }
    '/_pages/kontakt': {
      id: '/_pages/kontakt'
      path: '/kontakt'
      fullPath: '/kontakt'
      preLoaderRoute: typeof PagesKontaktRouteImport
      parentRoute: typeof PagesRoute
    }
    '/_pages/datenschutz': {
      id: '/_pages/datenschutz'
      path: '/datenschutz'
      fullPath: '/datenschutz'
      preLoaderRoute: typeof PagesDatenschutzRouteImport
      parentRoute: typeof PagesRoute
    }
    '/_pages/access-denied': {
      id: '/_pages/access-denied'
      path: '/access-denied'
      fullPath: '/access-denied'
      preLoaderRoute: typeof PagesAccessDeniedRouteImport
      parentRoute: typeof PagesRoute
    }
    '/admin/uploads/': {
      id: '/admin/uploads/'
      path: '/'
      fullPath: '/admin/uploads/'
      preLoaderRoute: typeof AdminUploadsIndexRouteImport
      parentRoute: typeof AdminUploadsRoute
    }
    '/admin/static-dataset-categories/': {
      id: '/admin/static-dataset-categories/'
      path: '/'
      fullPath: '/admin/static-dataset-categories/'
      preLoaderRoute: typeof AdminStaticDatasetCategoriesIndexRouteImport
      parentRoute: typeof AdminStaticDatasetCategoriesRoute
    }
    '/admin/regions/': {
      id: '/admin/regions/'
      path: '/'
      fullPath: '/admin/regions/'
      preLoaderRoute: typeof AdminRegionsIndexRouteImport
      parentRoute: typeof AdminRegionsRoute
    }
    '/admin/qa-configs/': {
      id: '/admin/qa-configs/'
      path: '/'
      fullPath: '/admin/qa-configs/'
      preLoaderRoute: typeof AdminQaConfigsIndexRouteImport
      parentRoute: typeof AdminQaConfigsRoute
    }
    '/admin/memberships/': {
      id: '/admin/memberships/'
      path: '/'
      fullPath: '/admin/memberships/'
      preLoaderRoute: typeof AdminMembershipsIndexRouteImport
      parentRoute: typeof AdminMembershipsRoute
    }
    '/api/uploads/create': {
      id: '/api/uploads/create'
      path: '/create'
      fullPath: '/api/uploads/create'
      preLoaderRoute: typeof ApiUploadsCreateRouteImport
      parentRoute: typeof ApiUploadsRoute
    }
    '/api/uploads/$slug': {
      id: '/api/uploads/$slug'
      path: '/$slug'
      fullPath: '/api/uploads/$slug'
      preLoaderRoute: typeof ApiUploadsSlugRouteImport
      parentRoute: typeof ApiUploadsRoute
    }
    '/api/sign-in/osm': {
      id: '/api/sign-in/osm'
      path: '/api/sign-in/osm'
      fullPath: '/api/sign-in/osm'
      preLoaderRoute: typeof ApiSignInOsmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/private/warm-cache': {
      id: '/api/private/warm-cache'
      path: '/api/private/warm-cache'
      fullPath: '/api/private/warm-cache'
      preLoaderRoute: typeof ApiPrivateWarmCacheRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/private/register-sql-functions': {
      id: '/api/private/register-sql-functions'
      path: '/api/private/register-sql-functions'
      fullPath: '/api/private/register-sql-functions'
      preLoaderRoute: typeof ApiPrivateRegisterSqlFunctionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/private/post-processing-statistics': {
      id: '/api/private/post-processing-statistics'
      path: '/api/private/post-processing-statistics'
      fullPath: '/api/private/post-processing-statistics'
      preLoaderRoute: typeof ApiPrivatePostProcessingStatisticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/private/post-processing-qa-update': {
      id: '/api/private/post-processing-qa-update'
      path: '/api/private/post-processing-qa-update'
      fullPath: '/api/private/post-processing-qa-update'
      preLoaderRoute: typeof ApiPrivatePostProcessingQaUpdateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/private/post-processing-hook': {
      id: '/api/private/post-processing-hook'
      path: '/api/private/post-processing-hook'
      fullPath: '/api/private/post-processing-hook'
      preLoaderRoute: typeof ApiPrivatePostProcessingHookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/private/generate-maproulette-tasks': {
      id: '/api/private/generate-maproulette-tasks'
      path: '/api/private/generate-maproulette-tasks'
      fullPath: '/api/private/generate-maproulette-tasks'
      preLoaderRoute: typeof ApiPrivateGenerateMaprouletteTasksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/osm-notes/rss': {
      id: '/api/osm-notes/rss'
      path: '/api/osm-notes/rss'
      fullPath: '/api/osm-notes/rss'
      preLoaderRoute: typeof ApiOsmNotesRssRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/notes/$regionSlug': {
      id: '/api/notes/$regionSlug'
      path: '/api/notes/$regionSlug'
      fullPath: '/api/notes/$regionSlug'
      preLoaderRoute: typeof ApiNotesRegionSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/uploads/$slug': {
      id: '/admin/uploads/$slug'
      path: '/$slug'
      fullPath: '/admin/uploads/$slug'
      preLoaderRoute: typeof AdminUploadsSlugRouteImport
      parentRoute: typeof AdminUploadsRoute
    }
    '/admin/static-dataset-categories/new': {
      id: '/admin/static-dataset-categories/new'
      path: '/new'
      fullPath: '/admin/static-dataset-categories/new'
      preLoaderRoute: typeof AdminStaticDatasetCategoriesNewRouteImport
      parentRoute: typeof AdminStaticDatasetCategoriesRoute
    }
    '/admin/static-dataset-categories/$categoryKey': {
      id: '/admin/static-dataset-categories/$categoryKey'
      path: '/$categoryKey'
      fullPath: '/admin/static-dataset-categories/$categoryKey'
      preLoaderRoute: typeof AdminStaticDatasetCategoriesCategoryKeyRouteImport
      parentRoute: typeof AdminStaticDatasetCategoriesRoute
    }
    '/admin/regions/new': {
      id: '/admin/regions/new'
      path: '/new'
      fullPath: '/admin/regions/new'
      preLoaderRoute: typeof AdminRegionsNewRouteImport
      parentRoute: typeof AdminRegionsRoute
    }
    '/admin/qa-configs/new': {
      id: '/admin/qa-configs/new'
      path: '/new'
      fullPath: '/admin/qa-configs/new'
      preLoaderRoute: typeof AdminQaConfigsNewRouteImport
      parentRoute: typeof AdminQaConfigsRoute
    }
    '/admin/memberships/new': {
      id: '/admin/memberships/new'
      path: '/new'
      fullPath: '/admin/memberships/new'
      preLoaderRoute: typeof AdminMembershipsNewRouteImport
      parentRoute: typeof AdminMembershipsRoute
    }
    '/_pages/settings/user': {
      id: '/_pages/settings/user'
      path: '/settings/user'
      fullPath: '/settings/user'
      preLoaderRoute: typeof PagesSettingsUserRouteImport
      parentRoute: typeof PagesRoute
    }
    '/_pages/docs/mapillary-coverage': {
      id: '/_pages/docs/mapillary-coverage'
      path: '/docs/mapillary-coverage'
      fullPath: '/docs/mapillary-coverage'
      preLoaderRoute: typeof PagesDocsMapillaryCoverageRouteImport
      parentRoute: typeof PagesRoute
    }
    '/_pages/docs/$tableName': {
      id: '/_pages/docs/$tableName'
      path: '/docs/$tableName'
      fullPath: '/docs/$tableName'
      preLoaderRoute: typeof PagesDocsTableNameRouteImport
      parentRoute: typeof PagesRoute
    }
    '/api/regions/$regionSlug/uploads-csv': {
      id: '/api/regions/$regionSlug/uploads-csv'
      path: '/$regionSlug/uploads-csv'
      fullPath: '/api/regions/$regionSlug/uploads-csv'
      preLoaderRoute: typeof ApiRegionsRegionSlugUploadsCsvRouteImport
      parentRoute: typeof ApiRegionsRoute
    }
    '/api/notes/$regionSlug/download': {
      id: '/api/notes/$regionSlug/download'
      path: '/download'
      fullPath: '/api/notes/$regionSlug/download'
      preLoaderRoute: typeof ApiNotesRegionSlugDownloadRouteImport
      parentRoute: typeof ApiNotesRegionSlugRoute
    }
    '/api/maproulette/statistic-proxy/$challengeId': {
      id: '/api/maproulette/statistic-proxy/$challengeId'
      path: '/api/maproulette/statistic-proxy/$challengeId'
      fullPath: '/api/maproulette/statistic-proxy/$challengeId'
      preLoaderRoute: typeof ApiMaprouletteStatisticProxyChallengeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/maproulette/data/test_tag_fix_two': {
      id: '/api/maproulette/data/test_tag_fix_two'
      path: '/api/maproulette/data/test_tag_fix_two'
      fullPath: '/api/maproulette/data/test_tag_fix_two'
      preLoaderRoute: typeof ApiMaprouletteDataTest_tag_fix_twoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/maproulette/data/test_tag_fix_cycleway-shared': {
      id: '/api/maproulette/data/test_tag_fix_cycleway-shared'
      path: '/api/maproulette/data/test_tag_fix_cycleway-shared'
      fullPath: '/api/maproulette/data/test_tag_fix_cycleway-shared'
      preLoaderRoute: typeof ApiMaprouletteDataTest_tag_fix_cyclewaySharedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/maproulette/data/test_tag_fix': {
      id: '/api/maproulette/data/test_tag_fix'
      path: '/api/maproulette/data/test_tag_fix'
      fullPath: '/api/maproulette/data/test_tag_fix'
      preLoaderRoute: typeof ApiMaprouletteDataTest_tag_fixRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/maproulette/data/$projectKey': {
      id: '/api/maproulette/data/$projectKey'
      path: '/api/maproulette/data/$projectKey'
      fullPath: '/api/maproulette/data/$projectKey'
      preLoaderRoute: typeof ApiMaprouletteDataProjectKeyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/export/$regionSlug/$tableName': {
      id: '/api/export/$regionSlug/$tableName'
      path: '/api/export/$regionSlug/$tableName'
      fullPath: '/api/export/$regionSlug/$tableName'
      preLoaderRoute: typeof ApiExportRegionSlugTableNameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/export-ogr/$regionSlug/$tableName': {
      id: '/api/export-ogr/$regionSlug/$tableName'
      path: '/api/export-ogr/$regionSlug/$tableName'
      fullPath: '/api/export-ogr/$regionSlug/$tableName'
      preLoaderRoute: typeof ApiExportOgrRegionSlugTableNameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/regions/$regionSlug/edit': {
      id: '/admin/regions/$regionSlug/edit'
      path: '/$regionSlug/edit'
      fullPath: '/admin/regions/$regionSlug/edit'
      preLoaderRoute: typeof AdminRegionsRegionSlugEditRouteImport
      parentRoute: typeof AdminRegionsRoute
    }
    '/admin/qa-configs/$id/edit': {
      id: '/admin/qa-configs/$id/edit'
      path: '/$id/edit'
      fullPath: '/admin/qa-configs/$id/edit'
      preLoaderRoute: typeof AdminQaConfigsIdEditRouteImport
      parentRoute: typeof AdminQaConfigsRoute
    }
    '/api/admin/qa-configs/$id/export-csv': {
      id: '/api/admin/qa-configs/$id/export-csv'
      path: '/api/admin/qa-configs/$id/export-csv'
      fullPath: '/api/admin/qa-configs/$id/export-csv'
      preLoaderRoute: typeof ApiAdminQaConfigsIdExportCsvRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface HomeRouteChildren {
  HomeIndexRoute: typeof HomeIndexRoute
}

const HomeRouteChildren: HomeRouteChildren = {
  HomeIndexRoute: HomeIndexRoute,
}

const HomeRouteWithChildren = HomeRoute._addFileChildren(HomeRouteChildren)

interface PagesRouteChildren {
  PagesAccessDeniedRoute: typeof PagesAccessDeniedRoute
  PagesDatenschutzRoute: typeof PagesDatenschutzRoute
  PagesKontaktRoute: typeof PagesKontaktRoute
  PagesOAuthErrorRoute: typeof PagesOAuthErrorRoute
  PagesDocsTableNameRoute: typeof PagesDocsTableNameRoute
  PagesDocsMapillaryCoverageRoute: typeof PagesDocsMapillaryCoverageRoute
  PagesSettingsUserRoute: typeof PagesSettingsUserRoute
}

const PagesRouteChildren: PagesRouteChildren = {
  PagesAccessDeniedRoute: PagesAccessDeniedRoute,
  PagesDatenschutzRoute: PagesDatenschutzRoute,
  PagesKontaktRoute: PagesKontaktRoute,
  PagesOAuthErrorRoute: PagesOAuthErrorRoute,
  PagesDocsTableNameRoute: PagesDocsTableNameRoute,
  PagesDocsMapillaryCoverageRoute: PagesDocsMapillaryCoverageRoute,
  PagesSettingsUserRoute: PagesSettingsUserRoute,
}

const PagesRouteWithChildren = PagesRoute._addFileChildren(PagesRouteChildren)

interface AdminMembershipsRouteChildren {
  AdminMembershipsNewRoute: typeof AdminMembershipsNewRoute
  AdminMembershipsIndexRoute: typeof AdminMembershipsIndexRoute
}

const AdminMembershipsRouteChildren: AdminMembershipsRouteChildren = {
  AdminMembershipsNewRoute: AdminMembershipsNewRoute,
  AdminMembershipsIndexRoute: AdminMembershipsIndexRoute,
}

const AdminMembershipsRouteWithChildren =
  AdminMembershipsRoute._addFileChildren(AdminMembershipsRouteChildren)

interface AdminQaConfigsRouteChildren {
  AdminQaConfigsNewRoute: typeof AdminQaConfigsNewRoute
  AdminQaConfigsIndexRoute: typeof AdminQaConfigsIndexRoute
  AdminQaConfigsIdEditRoute: typeof AdminQaConfigsIdEditRoute
}

const AdminQaConfigsRouteChildren: AdminQaConfigsRouteChildren = {
  AdminQaConfigsNewRoute: AdminQaConfigsNewRoute,
  AdminQaConfigsIndexRoute: AdminQaConfigsIndexRoute,
  AdminQaConfigsIdEditRoute: AdminQaConfigsIdEditRoute,
}

const AdminQaConfigsRouteWithChildren = AdminQaConfigsRoute._addFileChildren(
  AdminQaConfigsRouteChildren,
)

interface AdminRegionsRouteChildren {
  AdminRegionsNewRoute: typeof AdminRegionsNewRoute
  AdminRegionsIndexRoute: typeof AdminRegionsIndexRoute
  AdminRegionsRegionSlugEditRoute: typeof AdminRegionsRegionSlugEditRoute
}

const AdminRegionsRouteChildren: AdminRegionsRouteChildren = {
  AdminRegionsNewRoute: AdminRegionsNewRoute,
  AdminRegionsIndexRoute: AdminRegionsIndexRoute,
  AdminRegionsRegionSlugEditRoute: AdminRegionsRegionSlugEditRoute,
}

const AdminRegionsRouteWithChildren = AdminRegionsRoute._addFileChildren(
  AdminRegionsRouteChildren,
)

interface AdminStaticDatasetCategoriesRouteChildren {
  AdminStaticDatasetCategoriesCategoryKeyRoute: typeof AdminStaticDatasetCategoriesCategoryKeyRoute
  AdminStaticDatasetCategoriesNewRoute: typeof AdminStaticDatasetCategoriesNewRoute
  AdminStaticDatasetCategoriesIndexRoute: typeof AdminStaticDatasetCategoriesIndexRoute
}

const AdminStaticDatasetCategoriesRouteChildren: AdminStaticDatasetCategoriesRouteChildren =
  {
    AdminStaticDatasetCategoriesCategoryKeyRoute:
      AdminStaticDatasetCategoriesCategoryKeyRoute,
    AdminStaticDatasetCategoriesNewRoute: AdminStaticDatasetCategoriesNewRoute,
    AdminStaticDatasetCategoriesIndexRoute:
      AdminStaticDatasetCategoriesIndexRoute,
  }

const AdminStaticDatasetCategoriesRouteWithChildren =
  AdminStaticDatasetCategoriesRoute._addFileChildren(
    AdminStaticDatasetCategoriesRouteChildren,
  )

interface AdminUploadsRouteChildren {
  AdminUploadsSlugRoute: typeof AdminUploadsSlugRoute
  AdminUploadsIndexRoute: typeof AdminUploadsIndexRoute
}

const AdminUploadsRouteChildren: AdminUploadsRouteChildren = {
  AdminUploadsSlugRoute: AdminUploadsSlugRoute,
  AdminUploadsIndexRoute: AdminUploadsIndexRoute,
}

const AdminUploadsRouteWithChildren = AdminUploadsRoute._addFileChildren(
  AdminUploadsRouteChildren,
)

interface AdminRouteChildren {
  AdminMembershipsRoute: typeof AdminMembershipsRouteWithChildren
  AdminQaConfigsRoute: typeof AdminQaConfigsRouteWithChildren
  AdminRegionsRoute: typeof AdminRegionsRouteWithChildren
  AdminStaticDatasetCategoriesRoute: typeof AdminStaticDatasetCategoriesRouteWithChildren
  AdminUploadsRoute: typeof AdminUploadsRouteWithChildren
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminMembershipsRoute: AdminMembershipsRouteWithChildren,
  AdminQaConfigsRoute: AdminQaConfigsRouteWithChildren,
  AdminRegionsRoute: AdminRegionsRouteWithChildren,
  AdminStaticDatasetCategoriesRoute:
    AdminStaticDatasetCategoriesRouteWithChildren,
  AdminUploadsRoute: AdminUploadsRouteWithChildren,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface PreviewRouteChildren {
  PreviewDefaultErrorRoute: typeof PreviewDefaultErrorRoute
  PreviewDefaultPendingRoute: typeof PreviewDefaultPendingRoute
  PreviewNotFoundRoute: typeof PreviewNotFoundRoute
  PreviewRegionErrorRoute: typeof PreviewRegionErrorRoute
  PreviewRegionPendingRoute: typeof PreviewRegionPendingRoute
  PreviewRootFallbackRoute: typeof PreviewRootFallbackRoute
}

const PreviewRouteChildren: PreviewRouteChildren = {
  PreviewDefaultErrorRoute: PreviewDefaultErrorRoute,
  PreviewDefaultPendingRoute: PreviewDefaultPendingRoute,
  PreviewNotFoundRoute: PreviewNotFoundRoute,
  PreviewRegionErrorRoute: PreviewRegionErrorRoute,
  PreviewRegionPendingRoute: PreviewRegionPendingRoute,
  PreviewRootFallbackRoute: PreviewRootFallbackRoute,
}

const PreviewRouteWithChildren =
  PreviewRoute._addFileChildren(PreviewRouteChildren)

interface RegionenRouteChildren {
  RegionenRegionSlugRoute: typeof RegionenRegionSlugRoute
  RegionenStatsRoute: typeof RegionenStatsRoute
  RegionenIndexRoute: typeof RegionenIndexRoute
}

const RegionenRouteChildren: RegionenRouteChildren = {
  RegionenRegionSlugRoute: RegionenRegionSlugRoute,
  RegionenStatsRoute: RegionenStatsRoute,
  RegionenIndexRoute: RegionenIndexRoute,
}

const RegionenRouteWithChildren = RegionenRoute._addFileChildren(
  RegionenRouteChildren,
)

interface ApiRegionsRouteChildren {
  ApiRegionsRegionSlugUploadsCsvRoute: typeof ApiRegionsRegionSlugUploadsCsvRoute
}

const ApiRegionsRouteChildren: ApiRegionsRouteChildren = {
  ApiRegionsRegionSlugUploadsCsvRoute: ApiRegionsRegionSlugUploadsCsvRoute,
}

const ApiRegionsRouteWithChildren = ApiRegionsRoute._addFileChildren(
  ApiRegionsRouteChildren,
)

interface ApiUploadsRouteChildren {
  ApiUploadsSlugRoute: typeof ApiUploadsSlugRoute
  ApiUploadsCreateRoute: typeof ApiUploadsCreateRoute
}

const ApiUploadsRouteChildren: ApiUploadsRouteChildren = {
  ApiUploadsSlugRoute: ApiUploadsSlugRoute,
  ApiUploadsCreateRoute: ApiUploadsCreateRoute,
}

const ApiUploadsRouteWithChildren = ApiUploadsRoute._addFileChildren(
  ApiUploadsRouteChildren,
)

interface ApiNotesRegionSlugRouteChildren {
  ApiNotesRegionSlugDownloadRoute: typeof ApiNotesRegionSlugDownloadRoute
}

const ApiNotesRegionSlugRouteChildren: ApiNotesRegionSlugRouteChildren = {
  ApiNotesRegionSlugDownloadRoute: ApiNotesRegionSlugDownloadRoute,
}

const ApiNotesRegionSlugRouteWithChildren =
  ApiNotesRegionSlugRoute._addFileChildren(ApiNotesRegionSlugRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  HomeRoute: HomeRouteWithChildren,
  PagesRoute: PagesRouteWithChildren,
  AdminRoute: AdminRouteWithChildren,
  PreviewRoute: PreviewRouteWithChildren,
  RegionenRoute: RegionenRouteWithChildren,
  ApiBoundaryRoute: ApiBoundaryRoute,
  ApiCampaignsRoute: ApiCampaignsRoute,
  ApiMapStyleRoute: ApiMapStyleRoute,
  ApiProcessingDatesRoute: ApiProcessingDatesRoute,
  ApiProcessingDatesMapillaryRoute: ApiProcessingDatesMapillaryRoute,
  ApiRegionsRoute: ApiRegionsRouteWithChildren,
  ApiStatsRoute: ApiStatsRoute,
  ApiUploadsRoute: ApiUploadsRouteWithChildren,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiNotesRegionSlugRoute: ApiNotesRegionSlugRouteWithChildren,
  ApiOsmNotesRssRoute: ApiOsmNotesRssRoute,
  ApiPrivateGenerateMaprouletteTasksRoute:
    ApiPrivateGenerateMaprouletteTasksRoute,
  ApiPrivatePostProcessingHookRoute: ApiPrivatePostProcessingHookRoute,
  ApiPrivatePostProcessingQaUpdateRoute: ApiPrivatePostProcessingQaUpdateRoute,
  ApiPrivatePostProcessingStatisticsRoute:
    ApiPrivatePostProcessingStatisticsRoute,
  ApiPrivateRegisterSqlFunctionsRoute: ApiPrivateRegisterSqlFunctionsRoute,
  ApiPrivateWarmCacheRoute: ApiPrivateWarmCacheRoute,
  ApiSignInOsmRoute: ApiSignInOsmRoute,
  ApiExportOgrRegionSlugTableNameRoute: ApiExportOgrRegionSlugTableNameRoute,
  ApiExportRegionSlugTableNameRoute: ApiExportRegionSlugTableNameRoute,
  ApiMaprouletteDataProjectKeyRoute: ApiMaprouletteDataProjectKeyRoute,
  ApiMaprouletteDataTest_tag_fixRoute: ApiMaprouletteDataTest_tag_fixRoute,
  ApiMaprouletteDataTest_tag_fix_cyclewaySharedRoute:
    ApiMaprouletteDataTest_tag_fix_cyclewaySharedRoute,
  ApiMaprouletteDataTest_tag_fix_twoRoute:
    ApiMaprouletteDataTest_tag_fix_twoRoute,
  ApiMaprouletteStatisticProxyChallengeIdRoute:
    ApiMaprouletteStatisticProxyChallengeIdRoute,
  ApiAdminQaConfigsIdExportCsvRoute: ApiAdminQaConfigsIdExportCsvRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
