/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegionenRouteImport } from './routes/regionen'
import { Route as PreviewRouteImport } from './routes/preview'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as PagesRouteImport } from './routes/_pages'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RegionenIndexRouteImport } from './routes/regionen/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as RegionenStatsRouteImport } from './routes/regionen/stats'
import { Route as RegionenRegionSlugRouteImport } from './routes/regionen/$regionSlug'
import { Route as PreviewRootFallbackRouteImport } from './routes/preview/root-fallback'
import { Route as PreviewRegionPendingRouteImport } from './routes/preview/region-pending'
import { Route as PreviewRegionErrorRouteImport } from './routes/preview/region-error'
import { Route as PreviewNotFoundRouteImport } from './routes/preview/not-found'
import { Route as PreviewDefaultPendingRouteImport } from './routes/preview/default-pending'
import { Route as PreviewDefaultErrorRouteImport } from './routes/preview/default-error'
import { Route as ApiUploadsRouteImport } from './routes/api/uploads'
import { Route as ApiStatsRouteImport } from './routes/api/stats'
import { Route as ApiRegionsRouteImport } from './routes/api/regions'
import { Route as ApiProcessingDatesMapillaryRouteImport } from './routes/api/processing-dates-mapillary'
import { Route as ApiProcessingDatesRouteImport } from './routes/api/processing-dates'
import { Route as ApiMapStyleRouteImport } from './routes/api/map-style'
import { Route as ApiCampaignsRouteImport } from './routes/api/campaigns'
import { Route as ApiBoundaryRouteImport } from './routes/api/boundary'
import { Route as AdminRegionsRouteImport } from './routes/admin/regions'
import { Route as AdminRegionContractsRouteImport } from './routes/admin/region-contracts'
import { Route as AdminQaConfigsRouteImport } from './routes/admin/qa-configs'
import { Route as AdminProcessingRouteImport } from './routes/admin/processing'
import { Route as AdminMembershipsRouteImport } from './routes/admin/memberships'
import { Route as AdminMapDatasetUploadsRouteImport } from './routes/admin/map-dataset-uploads'
import { Route as AdminMapDatasetCategoriesRouteImport } from './routes/admin/map-dataset-categories'
import { Route as AdminDataSchemaRouteImport } from './routes/admin/data-schema'
import { Route as AdminAuditLogRouteImport } from './routes/admin/audit-log'
import { Route as AdminApiTokensRouteImport } from './routes/admin/api-tokens'
import { Route as PagesOAuthErrorRouteImport } from './routes/_pages/oAuthError'
import { Route as PagesKontaktRouteImport } from './routes/_pages/kontakt'
import { Route as PagesDatenschutzRouteImport } from './routes/_pages/datenschutz'
import { Route as PagesAccessDeniedRouteImport } from './routes/_pages/access-denied'
import { Route as AdminRegionsIndexRouteImport } from './routes/admin/regions/index'
import { Route as AdminRegionContractsIndexRouteImport } from './routes/admin/region-contracts/index'
import { Route as AdminQaConfigsIndexRouteImport } from './routes/admin/qa-configs/index'
import { Route as AdminProcessingIndexRouteImport } from './routes/admin/processing/index'
import { Route as AdminMembershipsIndexRouteImport } from './routes/admin/memberships/index'
import { Route as AdminMapDatasetUploadsIndexRouteImport } from './routes/admin/map-dataset-uploads/index'
import { Route as AdminMapDatasetCategoriesIndexRouteImport } from './routes/admin/map-dataset-categories/index'
import { Route as ApiUploadsCreateRouteImport } from './routes/api/uploads.create'
import { Route as ApiUploadsSlugRouteImport } from './routes/api/uploads.$slug'
import { Route as ApiSignInOsmRouteImport } from './routes/api/sign-in.osm'
import { Route as ApiPrivateWarmCacheRouteImport } from './routes/api/private/warm-cache'
import { Route as ApiPrivateRegisterSqlFunctionsRouteImport } from './routes/api/private/register-sql-functions'
import { Route as ApiPrivateRegionsRouteImport } from './routes/api/private/regions'
import { Route as ApiPrivatePostProcessingQaUpdateRouteImport } from './routes/api/private/post-processing-qa-update'
import { Route as ApiPrivatePostProcessingHookRouteImport } from './routes/api/private/post-processing-hook'
import { Route as ApiPrivateGenerateMaprouletteTasksRouteImport } from './routes/api/private/generate-maproulette-tasks'
import { Route as ApiOsmNotesRssRouteImport } from './routes/api/osm-notes.rss'
import { Route as ApiNotesRegionSlugRouteImport } from './routes/api/notes.$regionSlug'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth.$'
import { Route as ApiAdminRegionsRouteImport } from './routes/api/admin/regions'
import { Route as ApiAdminRegionUploadsRouteImport } from './routes/api/admin/region-uploads'
import { Route as ApiAdminProcessingRouteImport } from './routes/api/admin/processing'
import { Route as ApiAdminAuditLogRouteImport } from './routes/api/admin/audit-log'
import { Route as AdminRegionsNewRouteImport } from './routes/admin/regions/new'
import { Route as AdminRegionContractsNewRouteImport } from './routes/admin/region-contracts/new'
import { Route as AdminQaConfigsNewRouteImport } from './routes/admin/qa-configs/new'
import { Route as AdminProcessingMetaIdRouteImport } from './routes/admin/processing/$metaId'
import { Route as AdminMembershipsNewRouteImport } from './routes/admin/memberships/new'
import { Route as AdminMapDatasetUploadsSlugRouteImport } from './routes/admin/map-dataset-uploads/$slug'
import { Route as AdminMapDatasetCategoriesNewRouteImport } from './routes/admin/map-dataset-categories/new'
import { Route as AdminMapDatasetCategoriesCategoryKeyRouteImport } from './routes/admin/map-dataset-categories/$categoryKey'
import { Route as PagesSettingsUserRouteImport } from './routes/_pages/settings.user'
import { Route as PagesDocsMapillaryCoverageRouteImport } from './routes/_pages/docs.mapillary-coverage'
import { Route as PagesDocsTableNameRouteImport } from './routes/_pages/docs.$tableName'
import { Route as ApiRegionsRegionSlugUploadsCsvRouteImport } from './routes/api/regions.$regionSlug.uploads-csv'
import { Route as ApiRegionUploadsIdFilenameRouteImport } from './routes/api/region-uploads.$id.$filename'
import { Route as ApiNotesRegionSlugDownloadRouteImport } from './routes/api/notes.$regionSlug.download'
import { Route as ApiMaprouletteStatisticProxyChallengeIdRouteImport } from './routes/api/maproulette.statistic-proxy.$challengeId'
import { Route as ApiMaprouletteDataTest_tag_fix_twoRouteImport } from './routes/api/maproulette.data.test_tag_fix_two'
import { Route as ApiMaprouletteDataTest_tag_fix_cyclewaySharedRouteImport } from './routes/api/maproulette.data.test_tag_fix_cycleway-shared'
import { Route as ApiMaprouletteDataTest_tag_fixRouteImport } from './routes/api/maproulette.data.test_tag_fix'
import { Route as ApiMaprouletteDataProjectKeyRouteImport } from './routes/api/maproulette.data.$projectKey'
import { Route as ApiExportRegionSlugTableNameRouteImport } from './routes/api/export.$regionSlug.$tableName'
import { Route as ApiExportOgrRegionSlugTableNameRouteImport } from './routes/api/export-ogr.$regionSlug.$tableName'
import { Route as ApiAdminRegionsSlugRouteImport } from './routes/api/admin/regions.$slug'
import { Route as ApiAdminRegionUploadsUploadRouteImport } from './routes/api/admin/region-uploads.upload'
import { Route as ApiAdminProcessingMetaIdRouteImport } from './routes/api/admin/processing.$metaId'
import { Route as ApiAdminDataSchemaImportRouteImport } from './routes/api/admin/data-schema.import'
import { Route as AdminRegionsRegionSlugEditRouteImport } from './routes/admin/regions/$regionSlug.edit'
import { Route as AdminRegionContractsSlugEditRouteImport } from './routes/admin/region-contracts/$slug.edit'
import { Route as AdminQaConfigsIdEditRouteImport } from './routes/admin/qa-configs/$id.edit'
import { Route as ApiAdminQaConfigsIdExportCsvRouteImport } from './routes/api/admin.qa-configs.$id.export-csv'

const RegionenRoute = RegionenRouteImport.update({
  id: '/regionen',
  path: '/regionen',
  getParentRoute: () => rootRouteImport,
} as any)
const PreviewRoute = PreviewRouteImport.update({
  id: '/preview',
  path: '/preview',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const PagesRoute = PagesRouteImport.update({
  id: '/_pages',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RegionenIndexRoute = RegionenIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => RegionenRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const RegionenStatsRoute = RegionenStatsRouteImport.update({
  id: '/stats',
  path: '/stats',
  getParentRoute: () => RegionenRoute,
} as any)
const RegionenRegionSlugRoute = RegionenRegionSlugRouteImport.update({
  id: '/$regionSlug',
  path: '/$regionSlug',
  getParentRoute: () => RegionenRoute,
} as any)
const PreviewRootFallbackRoute = PreviewRootFallbackRouteImport.update({
  id: '/root-fallback',
  path: '/root-fallback',
  getParentRoute: () => PreviewRoute,
} as any)
const PreviewRegionPendingRoute = PreviewRegionPendingRouteImport.update({
  id: '/region-pending',
  path: '/region-pending',
  getParentRoute: () => PreviewRoute,
} as any)
const PreviewRegionErrorRoute = PreviewRegionErrorRouteImport.update({
  id: '/region-error',
  path: '/region-error',
  getParentRoute: () => PreviewRoute,
} as any)
const PreviewNotFoundRoute = PreviewNotFoundRouteImport.update({
  id: '/not-found',
  path: '/not-found',
  getParentRoute: () => PreviewRoute,
} as any)
const PreviewDefaultPendingRoute = PreviewDefaultPendingRouteImport.update({
  id: '/default-pending',
  path: '/default-pending',
  getParentRoute: () => PreviewRoute,
} as any)
const PreviewDefaultErrorRoute = PreviewDefaultErrorRouteImport.update({
  id: '/default-error',
  path: '/default-error',
  getParentRoute: () => PreviewRoute,
} as any)
const ApiUploadsRoute = ApiUploadsRouteImport.update({
  id: '/api/uploads',
  path: '/api/uploads',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStatsRoute = ApiStatsRouteImport.update({
  id: '/api/stats',
  path: '/api/stats',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRegionsRoute = ApiRegionsRouteImport.update({
  id: '/api/regions',
  path: '/api/regions',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProcessingDatesMapillaryRoute =
  ApiProcessingDatesMapillaryRouteImport.update({
    id: '/api/processing-dates-mapillary',
    path: '/api/processing-dates-mapillary',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiProcessingDatesRoute = ApiProcessingDatesRouteImport.update({
  id: '/api/processing-dates',
  path: '/api/processing-dates',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMapStyleRoute = ApiMapStyleRouteImport.update({
  id: '/api/map-style',
  path: '/api/map-style',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCampaignsRoute = ApiCampaignsRouteImport.update({
  id: '/api/campaigns',
  path: '/api/campaigns',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBoundaryRoute = ApiBoundaryRouteImport.update({
  id: '/api/boundary',
  path: '/api/boundary',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRegionsRoute = AdminRegionsRouteImport.update({
  id: '/regions',
  path: '/regions',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRegionContractsRoute = AdminRegionContractsRouteImport.update({
  id: '/region-contracts',
  path: '/region-contracts',
  getParentRoute: () => AdminRoute,
} as any)
const AdminQaConfigsRoute = AdminQaConfigsRouteImport.update({
  id: '/qa-configs',
  path: '/qa-configs',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProcessingRoute = AdminProcessingRouteImport.update({
  id: '/processing',
  path: '/processing',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMembershipsRoute = AdminMembershipsRouteImport.update({
  id: '/memberships',
  path: '/memberships',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMapDatasetUploadsRoute = AdminMapDatasetUploadsRouteImport.update({
  id: '/map-dataset-uploads',
  path: '/map-dataset-uploads',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMapDatasetCategoriesRoute =
  AdminMapDatasetCategoriesRouteImport.update({
    id: '/map-dataset-categories',
    path: '/map-dataset-categories',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminDataSchemaRoute = AdminDataSchemaRouteImport.update({
  id: '/data-schema',
  path: '/data-schema',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAuditLogRoute = AdminAuditLogRouteImport.update({
  id: '/audit-log',
  path: '/audit-log',
  getParentRoute: () => AdminRoute,
} as any)
const AdminApiTokensRoute = AdminApiTokensRouteImport.update({
  id: '/api-tokens',
  path: '/api-tokens',
  getParentRoute: () => AdminRoute,
} as any)
const PagesOAuthErrorRoute = PagesOAuthErrorRouteImport.update({
  id: '/oAuthError',
  path: '/oAuthError',
  getParentRoute: () => PagesRoute,
} as any)
const PagesKontaktRoute = PagesKontaktRouteImport.update({
  id: '/kontakt',
  path: '/kontakt',
  getParentRoute: () => PagesRoute,
} as any)
const PagesDatenschutzRoute = PagesDatenschutzRouteImport.update({
  id: '/datenschutz',
  path: '/datenschutz',
  getParentRoute: () => PagesRoute,
} as any)
const PagesAccessDeniedRoute = PagesAccessDeniedRouteImport.update({
  id: '/access-denied',
  path: '/access-denied',
  getParentRoute: () => PagesRoute,
} as any)
const AdminRegionsIndexRoute = AdminRegionsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRegionsRoute,
} as any)
const AdminRegionContractsIndexRoute =
  AdminRegionContractsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AdminRegionContractsRoute,
  } as any)
const AdminQaConfigsIndexRoute = AdminQaConfigsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminQaConfigsRoute,
} as any)
const AdminProcessingIndexRoute = AdminProcessingIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminProcessingRoute,
} as any)
const AdminMembershipsIndexRoute = AdminMembershipsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminMembershipsRoute,
} as any)
const AdminMapDatasetUploadsIndexRoute =
  AdminMapDatasetUploadsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AdminMapDatasetUploadsRoute,
  } as any)
const AdminMapDatasetCategoriesIndexRoute =
  AdminMapDatasetCategoriesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AdminMapDatasetCategoriesRoute,
  } as any)
const ApiUploadsCreateRoute = ApiUploadsCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => ApiUploadsRoute,
} as any)
const ApiUploadsSlugRoute = ApiUploadsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ApiUploadsRoute,
} as any)
const ApiSignInOsmRoute = ApiSignInOsmRouteImport.update({
  id: '/api/sign-in/osm',
  path: '/api/sign-in/osm',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPrivateWarmCacheRoute = ApiPrivateWarmCacheRouteImport.update({
  id: '/api/private/warm-cache',
  path: '/api/private/warm-cache',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPrivateRegisterSqlFunctionsRoute =
  ApiPrivateRegisterSqlFunctionsRouteImport.update({
    id: '/api/private/register-sql-functions',
    path: '/api/private/register-sql-functions',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPrivateRegionsRoute = ApiPrivateRegionsRouteImport.update({
  id: '/api/private/regions',
  path: '/api/private/regions',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPrivatePostProcessingQaUpdateRoute =
  ApiPrivatePostProcessingQaUpdateRouteImport.update({
    id: '/api/private/post-processing-qa-update',
    path: '/api/private/post-processing-qa-update',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPrivatePostProcessingHookRoute =
  ApiPrivatePostProcessingHookRouteImport.update({
    id: '/api/private/post-processing-hook',
    path: '/api/private/post-processing-hook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPrivateGenerateMaprouletteTasksRoute =
  ApiPrivateGenerateMaprouletteTasksRouteImport.update({
    id: '/api/private/generate-maproulette-tasks',
    path: '/api/private/generate-maproulette-tasks',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiOsmNotesRssRoute = ApiOsmNotesRssRouteImport.update({
  id: '/api/osm-notes/rss',
  path: '/api/osm-notes/rss',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiNotesRegionSlugRoute = ApiNotesRegionSlugRouteImport.update({
  id: '/api/notes/$regionSlug',
  path: '/api/notes/$regionSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminRegionsRoute = ApiAdminRegionsRouteImport.update({
  id: '/api/admin/regions',
  path: '/api/admin/regions',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminRegionUploadsRoute = ApiAdminRegionUploadsRouteImport.update({
  id: '/api/admin/region-uploads',
  path: '/api/admin/region-uploads',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminProcessingRoute = ApiAdminProcessingRouteImport.update({
  id: '/api/admin/processing',
  path: '/api/admin/processing',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminAuditLogRoute = ApiAdminAuditLogRouteImport.update({
  id: '/api/admin/audit-log',
  path: '/api/admin/audit-log',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRegionsNewRoute = AdminRegionsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AdminRegionsRoute,
} as any)
const AdminRegionContractsNewRoute = AdminRegionContractsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AdminRegionContractsRoute,
} as any)
const AdminQaConfigsNewRoute = AdminQaConfigsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AdminQaConfigsRoute,
} as any)
const AdminProcessingMetaIdRoute = AdminProcessingMetaIdRouteImport.update({
  id: '/$metaId',
  path: '/$metaId',
  getParentRoute: () => AdminProcessingRoute,
} as any)
const AdminMembershipsNewRoute = AdminMembershipsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AdminMembershipsRoute,
} as any)
const AdminMapDatasetUploadsSlugRoute =
  AdminMapDatasetUploadsSlugRouteImport.update({
    id: '/$slug',
    path: '/$slug',
    getParentRoute: () => AdminMapDatasetUploadsRoute,
  } as any)
const AdminMapDatasetCategoriesNewRoute =
  AdminMapDatasetCategoriesNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => AdminMapDatasetCategoriesRoute,
  } as any)
const AdminMapDatasetCategoriesCategoryKeyRoute =
  AdminMapDatasetCategoriesCategoryKeyRouteImport.update({
    id: '/$categoryKey',
    path: '/$categoryKey',
    getParentRoute: () => AdminMapDatasetCategoriesRoute,
  } as any)
const PagesSettingsUserRoute = PagesSettingsUserRouteImport.update({
  id: '/settings/user',
  path: '/settings/user',
  getParentRoute: () => PagesRoute,
} as any)
const PagesDocsMapillaryCoverageRoute =
  PagesDocsMapillaryCoverageRouteImport.update({
    id: '/docs/mapillary-coverage',
    path: '/docs/mapillary-coverage',
    getParentRoute: () => PagesRoute,
  } as any)
const PagesDocsTableNameRoute = PagesDocsTableNameRouteImport.update({
  id: '/docs/$tableName',
  path: '/docs/$tableName',
  getParentRoute: () => PagesRoute,
} as any)
const ApiRegionsRegionSlugUploadsCsvRoute =
  ApiRegionsRegionSlugUploadsCsvRouteImport.update({
    id: '/$regionSlug/uploads-csv',
    path: '/$regionSlug/uploads-csv',
    getParentRoute: () => ApiRegionsRoute,
  } as any)
const ApiRegionUploadsIdFilenameRoute =
  ApiRegionUploadsIdFilenameRouteImport.update({
    id: '/api/region-uploads/$id/$filename',
    path: '/api/region-uploads/$id/$filename',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiNotesRegionSlugDownloadRoute =
  ApiNotesRegionSlugDownloadRouteImport.update({
    id: '/download',
    path: '/download',
    getParentRoute: () => ApiNotesRegionSlugRoute,
  } as any)
const ApiMaprouletteStatisticProxyChallengeIdRoute =
  ApiMaprouletteStatisticProxyChallengeIdRouteImport.update({
    id: '/api/maproulette/statistic-proxy/$challengeId',
    path: '/api/maproulette/statistic-proxy/$challengeId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiMaprouletteDataTest_tag_fix_twoRoute =
  ApiMaprouletteDataTest_tag_fix_twoRouteImport.update({
    id: '/api/maproulette/data/test_tag_fix_two',
    path: '/api/maproulette/data/test_tag_fix_two',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiMaprouletteDataTest_tag_fix_cyclewaySharedRoute =
  ApiMaprouletteDataTest_tag_fix_cyclewaySharedRouteImport.update({
    id: '/api/maproulette/data/test_tag_fix_cycleway-shared',
    path: '/api/maproulette/data/test_tag_fix_cycleway-shared',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiMaprouletteDataTest_tag_fixRoute =
  ApiMaprouletteDataTest_tag_fixRouteImport.update({
    id: '/api/maproulette/data/test_tag_fix',
    path: '/api/maproulette/data/test_tag_fix',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiMaprouletteDataProjectKeyRoute =
  ApiMaprouletteDataProjectKeyRouteImport.update({
    id: '/api/maproulette/data/$projectKey',
    path: '/api/maproulette/data/$projectKey',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiExportRegionSlugTableNameRoute =
  ApiExportRegionSlugTableNameRouteImport.update({
    id: '/api/export/$regionSlug/$tableName',
    path: '/api/export/$regionSlug/$tableName',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiExportOgrRegionSlugTableNameRoute =
  ApiExportOgrRegionSlugTableNameRouteImport.update({
    id: '/api/export-ogr/$regionSlug/$tableName',
    path: '/api/export-ogr/$regionSlug/$tableName',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAdminRegionsSlugRoute = ApiAdminRegionsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ApiAdminRegionsRoute,
} as any)
const ApiAdminRegionUploadsUploadRoute =
  ApiAdminRegionUploadsUploadRouteImport.update({
    id: '/upload',
    path: '/upload',
    getParentRoute: () => ApiAdminRegionUploadsRoute,
  } as any)
const ApiAdminProcessingMetaIdRoute =
  ApiAdminProcessingMetaIdRouteImport.update({
    id: '/$metaId',
    path: '/$metaId',
    getParentRoute: () => ApiAdminProcessingRoute,
  } as any)
const ApiAdminDataSchemaImportRoute =
  ApiAdminDataSchemaImportRouteImport.update({
    id: '/api/admin/data-schema/import',
    path: '/api/admin/data-schema/import',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminRegionsRegionSlugEditRoute =
  AdminRegionsRegionSlugEditRouteImport.update({
    id: '/$regionSlug/edit',
    path: '/$regionSlug/edit',
    getParentRoute: () => AdminRegionsRoute,
  } as any)
const AdminRegionContractsSlugEditRoute =
  AdminRegionContractsSlugEditRouteImport.update({
    id: '/$slug/edit',
    path: '/$slug/edit',
    getParentRoute: () => AdminRegionContractsRoute,
  } as any)
const AdminQaConfigsIdEditRoute = AdminQaConfigsIdEditRouteImport.update({
  id: '/$id/edit',
  path: '/$id/edit',
  getParentRoute: () => AdminQaConfigsRoute,
} as any)
const ApiAdminQaConfigsIdExportCsvRoute =
  ApiAdminQaConfigsIdExportCsvRouteImport.update({
    id: '/api/admin/qa-configs/$id/export-csv',
    path: '/api/admin/qa-configs/$id/export-csv',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/mcp': typeof McpRoute
  '/preview': typeof PreviewRouteWithChildren
  '/regionen': typeof RegionenRouteWithChildren
  '/access-denied': typeof PagesAccessDeniedRoute
  '/datenschutz': typeof PagesDatenschutzRoute
  '/kontakt': typeof PagesKontaktRoute
  '/oAuthError': typeof PagesOAuthErrorRoute
  '/admin/api-tokens': typeof AdminApiTokensRoute
  '/admin/audit-log': typeof AdminAuditLogRoute
  '/admin/data-schema': typeof AdminDataSchemaRoute
  '/admin/map-dataset-categories': typeof AdminMapDatasetCategoriesRouteWithChildren
  '/admin/map-dataset-uploads': typeof AdminMapDatasetUploadsRouteWithChildren
  '/admin/memberships': typeof AdminMembershipsRouteWithChildren
  '/admin/processing': typeof AdminProcessingRouteWithChildren
  '/admin/qa-configs': typeof AdminQaConfigsRouteWithChildren
  '/admin/region-contracts': typeof AdminRegionContractsRouteWithChildren
  '/admin/regions': typeof AdminRegionsRouteWithChildren
  '/api/boundary': typeof ApiBoundaryRoute
  '/api/campaigns': typeof ApiCampaignsRoute
  '/api/map-style': typeof ApiMapStyleRoute
  '/api/processing-dates': typeof ApiProcessingDatesRoute
  '/api/processing-dates-mapillary': typeof ApiProcessingDatesMapillaryRoute
  '/api/regions': typeof ApiRegionsRouteWithChildren
  '/api/stats': typeof ApiStatsRoute
  '/api/uploads': typeof ApiUploadsRouteWithChildren
  '/preview/default-error': typeof PreviewDefaultErrorRoute
  '/preview/default-pending': typeof PreviewDefaultPendingRoute
  '/preview/not-found': typeof PreviewNotFoundRoute
  '/preview/region-error': typeof PreviewRegionErrorRoute
  '/preview/region-pending': typeof PreviewRegionPendingRoute
  '/preview/root-fallback': typeof PreviewRootFallbackRoute
  '/regionen/$regionSlug': typeof RegionenRegionSlugRoute
  '/regionen/stats': typeof RegionenStatsRoute
  '/admin/': typeof AdminIndexRoute
  '/regionen/': typeof RegionenIndexRoute
  '/docs/$tableName': typeof PagesDocsTableNameRoute
  '/docs/mapillary-coverage': typeof PagesDocsMapillaryCoverageRoute
  '/settings/user': typeof PagesSettingsUserRoute
  '/admin/map-dataset-categories/$categoryKey': typeof AdminMapDatasetCategoriesCategoryKeyRoute
  '/admin/map-dataset-categories/new': typeof AdminMapDatasetCategoriesNewRoute
  '/admin/map-dataset-uploads/$slug': typeof AdminMapDatasetUploadsSlugRoute
  '/admin/memberships/new': typeof AdminMembershipsNewRoute
  '/admin/processing/$metaId': typeof AdminProcessingMetaIdRoute
  '/admin/qa-configs/new': typeof AdminQaConfigsNewRoute
  '/admin/region-contracts/new': typeof AdminRegionContractsNewRoute
  '/admin/regions/new': typeof AdminRegionsNewRoute
  '/api/admin/audit-log': typeof ApiAdminAuditLogRoute
  '/api/admin/processing': typeof ApiAdminProcessingRouteWithChildren
  '/api/admin/region-uploads': typeof ApiAdminRegionUploadsRouteWithChildren
  '/api/admin/regions': typeof ApiAdminRegionsRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/notes/$regionSlug': typeof ApiNotesRegionSlugRouteWithChildren
  '/api/osm-notes/rss': typeof ApiOsmNotesRssRoute
  '/api/private/generate-maproulette-tasks': typeof ApiPrivateGenerateMaprouletteTasksRoute
  '/api/private/post-processing-hook': typeof ApiPrivatePostProcessingHookRoute
  '/api/private/post-processing-qa-update': typeof ApiPrivatePostProcessingQaUpdateRoute
  '/api/private/regions': typeof ApiPrivateRegionsRoute
  '/api/private/register-sql-functions': typeof ApiPrivateRegisterSqlFunctionsRoute
  '/api/private/warm-cache': typeof ApiPrivateWarmCacheRoute
  '/api/sign-in/osm': typeof ApiSignInOsmRoute
  '/api/uploads/$slug': typeof ApiUploadsSlugRoute
  '/api/uploads/create': typeof ApiUploadsCreateRoute
  '/admin/map-dataset-categories/': typeof AdminMapDatasetCategoriesIndexRoute
  '/admin/map-dataset-uploads/': typeof AdminMapDatasetUploadsIndexRoute
  '/admin/memberships/': typeof AdminMembershipsIndexRoute
  '/admin/processing/': typeof AdminProcessingIndexRoute
  '/admin/qa-configs/': typeof AdminQaConfigsIndexRoute
  '/admin/region-contracts/': typeof AdminRegionContractsIndexRoute
  '/admin/regions/': typeof AdminRegionsIndexRoute
  '/admin/qa-configs/$id/edit': typeof AdminQaConfigsIdEditRoute
  '/admin/region-contracts/$slug/edit': typeof AdminRegionContractsSlugEditRoute
  '/admin/regions/$regionSlug/edit': typeof AdminRegionsRegionSlugEditRoute
  '/api/admin/data-schema/import': typeof ApiAdminDataSchemaImportRoute
  '/api/admin/processing/$metaId': typeof ApiAdminProcessingMetaIdRoute
  '/api/admin/region-uploads/upload': typeof ApiAdminRegionUploadsUploadRoute
  '/api/admin/regions/$slug': typeof ApiAdminRegionsSlugRoute
  '/api/export-ogr/$regionSlug/$tableName': typeof ApiExportOgrRegionSlugTableNameRoute
  '/api/export/$regionSlug/$tableName': typeof ApiExportRegionSlugTableNameRoute
  '/api/maproulette/data/$projectKey': typeof ApiMaprouletteDataProjectKeyRoute
  '/api/maproulette/data/test_tag_fix': typeof ApiMaprouletteDataTest_tag_fixRoute
  '/api/maproulette/data/test_tag_fix_cycleway-shared': typeof ApiMaprouletteDataTest_tag_fix_cyclewaySharedRoute
  '/api/maproulette/data/test_tag_fix_two': typeof ApiMaprouletteDataTest_tag_fix_twoRoute
  '/api/maproulette/statistic-proxy/$challengeId': typeof ApiMaprouletteStatisticProxyChallengeIdRoute
  '/api/notes/$regionSlug/download': typeof ApiNotesRegionSlugDownloadRoute
  '/api/region-uploads/$id/$filename': typeof ApiRegionUploadsIdFilenameRoute
  '/api/regions/$regionSlug/uploads-csv': typeof ApiRegionsRegionSlugUploadsCsvRoute
  '/api/admin/qa-configs/$id/export-csv': typeof ApiAdminQaConfigsIdExportCsvRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/mcp': typeof McpRoute
  '/preview': typeof PreviewRouteWithChildren
  '/access-denied': typeof PagesAccessDeniedRoute
  '/datenschutz': typeof PagesDatenschutzRoute
  '/kontakt': typeof PagesKontaktRoute
  '/oAuthError': typeof PagesOAuthErrorRoute
  '/admin/api-tokens': typeof AdminApiTokensRoute
  '/admin/audit-log': typeof AdminAuditLogRoute
  '/admin/data-schema': typeof AdminDataSchemaRoute
  '/api/boundary': typeof ApiBoundaryRoute
  '/api/campaigns': typeof ApiCampaignsRoute
  '/api/map-style': typeof ApiMapStyleRoute
  '/api/processing-dates': typeof ApiProcessingDatesRoute
  '/api/processing-dates-mapillary': typeof ApiProcessingDatesMapillaryRoute
  '/api/regions': typeof ApiRegionsRouteWithChildren
  '/api/stats': typeof ApiStatsRoute
  '/api/uploads': typeof ApiUploadsRouteWithChildren
  '/preview/default-error': typeof PreviewDefaultErrorRoute
  '/preview/default-pending': typeof PreviewDefaultPendingRoute
  '/preview/not-found': typeof PreviewNotFoundRoute
  '/preview/region-error': typeof PreviewRegionErrorRoute
  '/preview/region-pending': typeof PreviewRegionPendingRoute
  '/preview/root-fallback': typeof PreviewRootFallbackRoute
  '/regionen/$regionSlug': typeof RegionenRegionSlugRoute
  '/regionen/stats': typeof RegionenStatsRoute
  '/admin': typeof AdminIndexRoute
  '/regionen': typeof RegionenIndexRoute
  '/docs/$tableName': typeof PagesDocsTableNameRoute
  '/docs/mapillary-coverage': typeof PagesDocsMapillaryCoverageRoute
  '/settings/user': typeof PagesSettingsUserRoute
  '/admin/map-dataset-categories/$categoryKey': typeof AdminMapDatasetCategoriesCategoryKeyRoute
  '/admin/map-dataset-categories/new': typeof AdminMapDatasetCategoriesNewRoute
  '/admin/map-dataset-uploads/$slug': typeof AdminMapDatasetUploadsSlugRoute
  '/admin/memberships/new': typeof AdminMembershipsNewRoute
  '/admin/processing/$metaId': typeof AdminProcessingMetaIdRoute
  '/admin/qa-configs/new': typeof AdminQaConfigsNewRoute
  '/admin/region-contracts/new': typeof AdminRegionContractsNewRoute
  '/admin/regions/new': typeof AdminRegionsNewRoute
  '/api/admin/audit-log': typeof ApiAdminAuditLogRoute
  '/api/admin/processing': typeof ApiAdminProcessingRouteWithChildren
  '/api/admin/region-uploads': typeof ApiAdminRegionUploadsRouteWithChildren
  '/api/admin/regions': typeof ApiAdminRegionsRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/notes/$regionSlug': typeof ApiNotesRegionSlugRouteWithChildren
  '/api/osm-notes/rss': typeof ApiOsmNotesRssRoute
  '/api/private/generate-maproulette-tasks': typeof ApiPrivateGenerateMaprouletteTasksRoute
  '/api/private/post-processing-hook': typeof ApiPrivatePostProcessingHookRoute
  '/api/private/post-processing-qa-update': typeof ApiPrivatePostProcessingQaUpdateRoute
  '/api/private/regions': typeof ApiPrivateRegionsRoute
  '/api/private/register-sql-functions': typeof ApiPrivateRegisterSqlFunctionsRoute
  '/api/private/warm-cache': typeof ApiPrivateWarmCacheRoute
  '/api/sign-in/osm': typeof ApiSignInOsmRoute
  '/api/uploads/$slug': typeof ApiUploadsSlugRoute
  '/api/uploads/create': typeof ApiUploadsCreateRoute
  '/admin/map-dataset-categories': typeof AdminMapDatasetCategoriesIndexRoute
  '/admin/map-dataset-uploads': typeof AdminMapDatasetUploadsIndexRoute
  '/admin/memberships': typeof AdminMembershipsIndexRoute
  '/admin/processing': typeof AdminProcessingIndexRoute
  '/admin/qa-configs': typeof AdminQaConfigsIndexRoute
  '/admin/region-contracts': typeof AdminRegionContractsIndexRoute
  '/admin/regions': typeof AdminRegionsIndexRoute
  '/admin/qa-configs/$id/edit': typeof AdminQaConfigsIdEditRoute
  '/admin/region-contracts/$slug/edit': typeof AdminRegionContractsSlugEditRoute
  '/admin/regions/$regionSlug/edit': typeof AdminRegionsRegionSlugEditRoute
  '/api/admin/data-schema/import': typeof ApiAdminDataSchemaImportRoute
  '/api/admin/processing/$metaId': typeof ApiAdminProcessingMetaIdRoute
  '/api/admin/region-uploads/upload': typeof ApiAdminRegionUploadsUploadRoute
  '/api/admin/regions/$slug': typeof ApiAdminRegionsSlugRoute
  '/api/export-ogr/$regionSlug/$tableName': typeof ApiExportOgrRegionSlugTableNameRoute
  '/api/export/$regionSlug/$tableName': typeof ApiExportRegionSlugTableNameRoute
  '/api/maproulette/data/$projectKey': typeof ApiMaprouletteDataProjectKeyRoute
  '/api/maproulette/data/test_tag_fix': typeof ApiMaprouletteDataTest_tag_fixRoute
  '/api/maproulette/data/test_tag_fix_cycleway-shared': typeof ApiMaprouletteDataTest_tag_fix_cyclewaySharedRoute
  '/api/maproulette/data/test_tag_fix_two': typeof ApiMaprouletteDataTest_tag_fix_twoRoute
  '/api/maproulette/statistic-proxy/$challengeId': typeof ApiMaprouletteStatisticProxyChallengeIdRoute
  '/api/notes/$regionSlug/download': typeof ApiNotesRegionSlugDownloadRoute
  '/api/region-uploads/$id/$filename': typeof ApiRegionUploadsIdFilenameRoute
  '/api/regions/$regionSlug/uploads-csv': typeof ApiRegionsRegionSlugUploadsCsvRoute
  '/api/admin/qa-configs/$id/export-csv': typeof ApiAdminQaConfigsIdExportCsvRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_pages': typeof PagesRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/mcp': typeof McpRoute
  '/preview': typeof PreviewRouteWithChildren
  '/regionen': typeof RegionenRouteWithChildren
  '/_pages/access-denied': typeof PagesAccessDeniedRoute
  '/_pages/datenschutz': typeof PagesDatenschutzRoute
  '/_pages/kontakt': typeof PagesKontaktRoute
  '/_pages/oAuthError': typeof PagesOAuthErrorRoute
  '/admin/api-tokens': typeof AdminApiTokensRoute
  '/admin/audit-log': typeof AdminAuditLogRoute
  '/admin/data-schema': typeof AdminDataSchemaRoute
  '/admin/map-dataset-categories': typeof AdminMapDatasetCategoriesRouteWithChildren
  '/admin/map-dataset-uploads': typeof AdminMapDatasetUploadsRouteWithChildren
  '/admin/memberships': typeof AdminMembershipsRouteWithChildren
  '/admin/processing': typeof AdminProcessingRouteWithChildren
  '/admin/qa-configs': typeof AdminQaConfigsRouteWithChildren
  '/admin/region-contracts': typeof AdminRegionContractsRouteWithChildren
  '/admin/regions': typeof AdminRegionsRouteWithChildren
  '/api/boundary': typeof ApiBoundaryRoute
  '/api/campaigns': typeof ApiCampaignsRoute
  '/api/map-style': typeof ApiMapStyleRoute
  '/api/processing-dates': typeof ApiProcessingDatesRoute
  '/api/processing-dates-mapillary': typeof ApiProcessingDatesMapillaryRoute
  '/api/regions': typeof ApiRegionsRouteWithChildren
  '/api/stats': typeof ApiStatsRoute
  '/api/uploads': typeof ApiUploadsRouteWithChildren
  '/preview/default-error': typeof PreviewDefaultErrorRoute
  '/preview/default-pending': typeof PreviewDefaultPendingRoute
  '/preview/not-found': typeof PreviewNotFoundRoute
  '/preview/region-error': typeof PreviewRegionErrorRoute
  '/preview/region-pending': typeof PreviewRegionPendingRoute
  '/preview/root-fallback': typeof PreviewRootFallbackRoute
  '/regionen/$regionSlug': typeof RegionenRegionSlugRoute
  '/regionen/stats': typeof RegionenStatsRoute
  '/admin/': typeof AdminIndexRoute
  '/regionen/': typeof RegionenIndexRoute
  '/_pages/docs/$tableName': typeof PagesDocsTableNameRoute
  '/_pages/docs/mapillary-coverage': typeof PagesDocsMapillaryCoverageRoute
  '/_pages/settings/user': typeof PagesSettingsUserRoute
  '/admin/map-dataset-categories/$categoryKey': typeof AdminMapDatasetCategoriesCategoryKeyRoute
  '/admin/map-dataset-categories/new': typeof AdminMapDatasetCategoriesNewRoute
  '/admin/map-dataset-uploads/$slug': typeof AdminMapDatasetUploadsSlugRoute
  '/admin/memberships/new': typeof AdminMembershipsNewRoute
  '/admin/processing/$metaId': typeof AdminProcessingMetaIdRoute
  '/admin/qa-configs/new': typeof AdminQaConfigsNewRoute
  '/admin/region-contracts/new': typeof AdminRegionContractsNewRoute
  '/admin/regions/new': typeof AdminRegionsNewRoute
  '/api/admin/audit-log': typeof ApiAdminAuditLogRoute
  '/api/admin/processing': typeof ApiAdminProcessingRouteWithChildren
  '/api/admin/region-uploads': typeof ApiAdminRegionUploadsRouteWithChildren
  '/api/admin/regions': typeof ApiAdminRegionsRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/notes/$regionSlug': typeof ApiNotesRegionSlugRouteWithChildren
  '/api/osm-notes/rss': typeof ApiOsmNotesRssRoute
  '/api/private/generate-maproulette-tasks': typeof ApiPrivateGenerateMaprouletteTasksRoute
  '/api/private/post-processing-hook': typeof ApiPrivatePostProcessingHookRoute
  '/api/private/post-processing-qa-update': typeof ApiPrivatePostProcessingQaUpdateRoute
  '/api/private/regions': typeof ApiPrivateRegionsRoute
  '/api/private/register-sql-functions': typeof ApiPrivateRegisterSqlFunctionsRoute
  '/api/private/warm-cache': typeof ApiPrivateWarmCacheRoute
  '/api/sign-in/osm': typeof ApiSignInOsmRoute
  '/api/uploads/$slug': typeof ApiUploadsSlugRoute
  '/api/uploads/create': typeof ApiUploadsCreateRoute
  '/admin/map-dataset-categories/': typeof AdminMapDatasetCategoriesIndexRoute
  '/admin/map-dataset-uploads/': typeof AdminMapDatasetUploadsIndexRoute
  '/admin/memberships/': typeof AdminMembershipsIndexRoute
  '/admin/processing/': typeof AdminProcessingIndexRoute
  '/admin/qa-configs/': typeof AdminQaConfigsIndexRoute
  '/admin/region-contracts/': typeof AdminRegionContractsIndexRoute
  '/admin/regions/': typeof AdminRegionsIndexRoute
  '/admin/qa-configs/$id/edit': typeof AdminQaConfigsIdEditRoute
  '/admin/region-contracts/$slug/edit': typeof AdminRegionContractsSlugEditRoute
  '/admin/regions/$regionSlug/edit': typeof AdminRegionsRegionSlugEditRoute
  '/api/admin/data-schema/import': typeof ApiAdminDataSchemaImportRoute
  '/api/admin/processing/$metaId': typeof ApiAdminProcessingMetaIdRoute
  '/api/admin/region-uploads/upload': typeof ApiAdminRegionUploadsUploadRoute
  '/api/admin/regions/$slug': typeof ApiAdminRegionsSlugRoute
  '/api/export-ogr/$regionSlug/$tableName': typeof ApiExportOgrRegionSlugTableNameRoute
  '/api/export/$regionSlug/$tableName': typeof ApiExportRegionSlugTableNameRoute
  '/api/maproulette/data/$projectKey': typeof ApiMaprouletteDataProjectKeyRoute
  '/api/maproulette/data/test_tag_fix': typeof ApiMaprouletteDataTest_tag_fixRoute
  '/api/maproulette/data/test_tag_fix_cycleway-shared': typeof ApiMaprouletteDataTest_tag_fix_cyclewaySharedRoute
  '/api/maproulette/data/test_tag_fix_two': typeof ApiMaprouletteDataTest_tag_fix_twoRoute
  '/api/maproulette/statistic-proxy/$challengeId': typeof ApiMaprouletteStatisticProxyChallengeIdRoute
  '/api/notes/$regionSlug/download': typeof ApiNotesRegionSlugDownloadRoute
  '/api/region-uploads/$id/$filename': typeof ApiRegionUploadsIdFilenameRoute
  '/api/regions/$regionSlug/uploads-csv': typeof ApiRegionsRegionSlugUploadsCsvRoute
  '/api/admin/qa-configs/$id/export-csv': typeof ApiAdminQaConfigsIdExportCsvRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/mcp'
    | '/preview'
    | '/regionen'
    | '/access-denied'
    | '/datenschutz'
    | '/kontakt'
    | '/oAuthError'
    | '/admin/api-tokens'
    | '/admin/audit-log'
    | '/admin/data-schema'
    | '/admin/map-dataset-categories'
    | '/admin/map-dataset-uploads'
    | '/admin/memberships'
    | '/admin/processing'
    | '/admin/qa-configs'
    | '/admin/region-contracts'
    | '/admin/regions'
    | '/api/boundary'
    | '/api/campaigns'
    | '/api/map-style'
    | '/api/processing-dates'
    | '/api/processing-dates-mapillary'
    | '/api/regions'
    | '/api/stats'
    | '/api/uploads'
    | '/preview/default-error'
    | '/preview/default-pending'
    | '/preview/not-found'
    | '/preview/region-error'
    | '/preview/region-pending'
    | '/preview/root-fallback'
    | '/regionen/$regionSlug'
    | '/regionen/stats'
    | '/admin/'
    | '/regionen/'
    | '/docs/$tableName'
    | '/docs/mapillary-coverage'
    | '/settings/user'
    | '/admin/map-dataset-categories/$categoryKey'
    | '/admin/map-dataset-categories/new'
    | '/admin/map-dataset-uploads/$slug'
    | '/admin/memberships/new'
    | '/admin/processing/$metaId'
    | '/admin/qa-configs/new'
    | '/admin/region-contracts/new'
    | '/admin/regions/new'
    | '/api/admin/audit-log'
    | '/api/admin/processing'
    | '/api/admin/region-uploads'
    | '/api/admin/regions'
    | '/api/auth/$'
    | '/api/notes/$regionSlug'
    | '/api/osm-notes/rss'
    | '/api/private/generate-maproulette-tasks'
    | '/api/private/post-processing-hook'
    | '/api/private/post-processing-qa-update'
    | '/api/private/regions'
    | '/api/private/register-sql-functions'
    | '/api/private/warm-cache'
    | '/api/sign-in/osm'
    | '/api/uploads/$slug'
    | '/api/uploads/create'
    | '/admin/map-dataset-categories/'
    | '/admin/map-dataset-uploads/'
    | '/admin/memberships/'
    | '/admin/processing/'
    | '/admin/qa-configs/'
    | '/admin/region-contracts/'
    | '/admin/regions/'
    | '/admin/qa-configs/$id/edit'
    | '/admin/region-contracts/$slug/edit'
    | '/admin/regions/$regionSlug/edit'
    | '/api/admin/data-schema/import'
    | '/api/admin/processing/$metaId'
    | '/api/admin/region-uploads/upload'
    | '/api/admin/regions/$slug'
    | '/api/export-ogr/$regionSlug/$tableName'
    | '/api/export/$regionSlug/$tableName'
    | '/api/maproulette/data/$projectKey'
    | '/api/maproulette/data/test_tag_fix'
    | '/api/maproulette/data/test_tag_fix_cycleway-shared'
    | '/api/maproulette/data/test_tag_fix_two'
    | '/api/maproulette/statistic-proxy/$challengeId'
    | '/api/notes/$regionSlug/download'
    | '/api/region-uploads/$id/$filename'
    | '/api/regions/$regionSlug/uploads-csv'
    | '/api/admin/qa-configs/$id/export-csv'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/mcp'
    | '/preview'
    | '/access-denied'
    | '/datenschutz'
    | '/kontakt'
    | '/oAuthError'
    | '/admin/api-tokens'
    | '/admin/audit-log'
    | '/admin/data-schema'
    | '/api/boundary'
    | '/api/campaigns'
    | '/api/map-style'
    | '/api/processing-dates'
    | '/api/processing-dates-mapillary'
    | '/api/regions'
    | '/api/stats'
    | '/api/uploads'
    | '/preview/default-error'
    | '/preview/default-pending'
    | '/preview/not-found'
    | '/preview/region-error'
    | '/preview/region-pending'
    | '/preview/root-fallback'
    | '/regionen/$regionSlug'
    | '/regionen/stats'
    | '/admin'
    | '/regionen'
    | '/docs/$tableName'
    | '/docs/mapillary-coverage'
    | '/settings/user'
    | '/admin/map-dataset-categories/$categoryKey'
    | '/admin/map-dataset-categories/new'
    | '/admin/map-dataset-uploads/$slug'
    | '/admin/memberships/new'
    | '/admin/processing/$metaId'
    | '/admin/qa-configs/new'
    | '/admin/region-contracts/new'
    | '/admin/regions/new'
    | '/api/admin/audit-log'
    | '/api/admin/processing'
    | '/api/admin/region-uploads'
    | '/api/admin/regions'
    | '/api/auth/$'
    | '/api/notes/$regionSlug'
    | '/api/osm-notes/rss'
    | '/api/private/generate-maproulette-tasks'
    | '/api/private/post-processing-hook'
    | '/api/private/post-processing-qa-update'
    | '/api/private/regions'
    | '/api/private/register-sql-functions'
    | '/api/private/warm-cache'
    | '/api/sign-in/osm'
    | '/api/uploads/$slug'
    | '/api/uploads/create'
    | '/admin/map-dataset-categories'
    | '/admin/map-dataset-uploads'
    | '/admin/memberships'
    | '/admin/processing'
    | '/admin/qa-configs'
    | '/admin/region-contracts'
    | '/admin/regions'
    | '/admin/qa-configs/$id/edit'
    | '/admin/region-contracts/$slug/edit'
    | '/admin/regions/$regionSlug/edit'
    | '/api/admin/data-schema/import'
    | '/api/admin/processing/$metaId'
    | '/api/admin/region-uploads/upload'
    | '/api/admin/regions/$slug'
    | '/api/export-ogr/$regionSlug/$tableName'
    | '/api/export/$regionSlug/$tableName'
    | '/api/maproulette/data/$projectKey'
    | '/api/maproulette/data/test_tag_fix'
    | '/api/maproulette/data/test_tag_fix_cycleway-shared'
    | '/api/maproulette/data/test_tag_fix_two'
    | '/api/maproulette/statistic-proxy/$challengeId'
    | '/api/notes/$regionSlug/download'
    | '/api/region-uploads/$id/$filename'
    | '/api/regions/$regionSlug/uploads-csv'
    | '/api/admin/qa-configs/$id/export-csv'
  id:
    | '__root__'
    | '/'
    | '/_pages'
    | '/admin'
    | '/mcp'
    | '/preview'
    | '/regionen'
    | '/_pages/access-denied'
    | '/_pages/datenschutz'
    | '/_pages/kontakt'
    | '/_pages/oAuthError'
    | '/admin/api-tokens'
    | '/admin/audit-log'
    | '/admin/data-schema'
    | '/admin/map-dataset-categories'
    | '/admin/map-dataset-uploads'
    | '/admin/memberships'
    | '/admin/processing'
    | '/admin/qa-configs'
    | '/admin/region-contracts'
    | '/admin/regions'
    | '/api/boundary'
    | '/api/campaigns'
    | '/api/map-style'
    | '/api/processing-dates'
    | '/api/processing-dates-mapillary'
    | '/api/regions'
    | '/api/stats'
    | '/api/uploads'
    | '/preview/default-error'
    | '/preview/default-pending'
    | '/preview/not-found'
    | '/preview/region-error'
    | '/preview/region-pending'
    | '/preview/root-fallback'
    | '/regionen/$regionSlug'
    | '/regionen/stats'
    | '/admin/'
    | '/regionen/'
    | '/_pages/docs/$tableName'
    | '/_pages/docs/mapillary-coverage'
    | '/_pages/settings/user'
    | '/admin/map-dataset-categories/$categoryKey'
    | '/admin/map-dataset-categories/new'
    | '/admin/map-dataset-uploads/$slug'
    | '/admin/memberships/new'
    | '/admin/processing/$metaId'
    | '/admin/qa-configs/new'
    | '/admin/region-contracts/new'
    | '/admin/regions/new'
    | '/api/admin/audit-log'
    | '/api/admin/processing'
    | '/api/admin/region-uploads'
    | '/api/admin/regions'
    | '/api/auth/$'
    | '/api/notes/$regionSlug'
    | '/api/osm-notes/rss'
    | '/api/private/generate-maproulette-tasks'
    | '/api/private/post-processing-hook'
    | '/api/private/post-processing-qa-update'
    | '/api/private/regions'
    | '/api/private/register-sql-functions'
    | '/api/private/warm-cache'
    | '/api/sign-in/osm'
    | '/api/uploads/$slug'
    | '/api/uploads/create'
    | '/admin/map-dataset-categories/'
    | '/admin/map-dataset-uploads/'
    | '/admin/memberships/'
    | '/admin/processing/'
    | '/admin/qa-configs/'
    | '/admin/region-contracts/'
    | '/admin/regions/'
    | '/admin/qa-configs/$id/edit'
    | '/admin/region-contracts/$slug/edit'
    | '/admin/regions/$regionSlug/edit'
    | '/api/admin/data-schema/import'
    | '/api/admin/processing/$metaId'
    | '/api/admin/region-uploads/upload'
    | '/api/admin/regions/$slug'
    | '/api/export-ogr/$regionSlug/$tableName'
    | '/api/export/$regionSlug/$tableName'
    | '/api/maproulette/data/$projectKey'
    | '/api/maproulette/data/test_tag_fix'
    | '/api/maproulette/data/test_tag_fix_cycleway-shared'
    | '/api/maproulette/data/test_tag_fix_two'
    | '/api/maproulette/statistic-proxy/$challengeId'
    | '/api/notes/$regionSlug/download'
    | '/api/region-uploads/$id/$filename'
    | '/api/regions/$regionSlug/uploads-csv'
    | '/api/admin/qa-configs/$id/export-csv'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PagesRoute: typeof PagesRouteWithChildren
  AdminRoute: typeof AdminRouteWithChildren
  McpRoute: typeof McpRoute
  PreviewRoute: typeof PreviewRouteWithChildren
  RegionenRoute: typeof RegionenRouteWithChildren
  ApiBoundaryRoute: typeof ApiBoundaryRoute
  ApiCampaignsRoute: typeof ApiCampaignsRoute
  ApiMapStyleRoute: typeof ApiMapStyleRoute
  ApiProcessingDatesRoute: typeof ApiProcessingDatesRoute
  ApiProcessingDatesMapillaryRoute: typeof ApiProcessingDatesMapillaryRoute
  ApiRegionsRoute: typeof ApiRegionsRouteWithChildren
  ApiStatsRoute: typeof ApiStatsRoute
  ApiUploadsRoute: typeof ApiUploadsRouteWithChildren
  ApiAdminAuditLogRoute: typeof ApiAdminAuditLogRoute
  ApiAdminProcessingRoute: typeof ApiAdminProcessingRouteWithChildren
  ApiAdminRegionUploadsRoute: typeof ApiAdminRegionUploadsRouteWithChildren
  ApiAdminRegionsRoute: typeof ApiAdminRegionsRouteWithChildren
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiNotesRegionSlugRoute: typeof ApiNotesRegionSlugRouteWithChildren
  ApiOsmNotesRssRoute: typeof ApiOsmNotesRssRoute
  ApiPrivateGenerateMaprouletteTasksRoute: typeof ApiPrivateGenerateMaprouletteTasksRoute
  ApiPrivatePostProcessingHookRoute: typeof ApiPrivatePostProcessingHookRoute
  ApiPrivatePostProcessingQaUpdateRoute: typeof ApiPrivatePostProcessingQaUpdateRoute
  ApiPrivateRegionsRoute: typeof ApiPrivateRegionsRoute
  ApiPrivateRegisterSqlFunctionsRoute: typeof ApiPrivateRegisterSqlFunctionsRoute
  ApiPrivateWarmCacheRoute: typeof ApiPrivateWarmCacheRoute
  ApiSignInOsmRoute: typeof ApiSignInOsmRoute
  ApiAdminDataSchemaImportRoute: typeof ApiAdminDataSchemaImportRoute
  ApiExportOgrRegionSlugTableNameRoute: typeof ApiExportOgrRegionSlugTableNameRoute
  ApiExportRegionSlugTableNameRoute: typeof ApiExportRegionSlugTableNameRoute
  ApiMaprouletteDataProjectKeyRoute: typeof ApiMaprouletteDataProjectKeyRoute
  ApiMaprouletteDataTest_tag_fixRoute: typeof ApiMaprouletteDataTest_tag_fixRoute
  ApiMaprouletteDataTest_tag_fix_cyclewaySharedRoute: typeof ApiMaprouletteDataTest_tag_fix_cyclewaySharedRoute
  ApiMaprouletteDataTest_tag_fix_twoRoute: typeof ApiMaprouletteDataTest_tag_fix_twoRoute
  ApiMaprouletteStatisticProxyChallengeIdRoute: typeof ApiMaprouletteStatisticProxyChallengeIdRoute
  ApiRegionUploadsIdFilenameRoute: typeof ApiRegionUploadsIdFilenameRoute
  ApiAdminQaConfigsIdExportCsvRoute: typeof ApiAdminQaConfigsIdExportCsvRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/regionen': {
      id: '/regionen'
      path: '/regionen'
      fullPath: '/regionen'
      preLoaderRoute: typeof RegionenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/preview': {
      id: '/preview'
      path: '/preview'
      fullPath: '/preview'
      preLoaderRoute: typeof PreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_pages': {
      id: '/_pages'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/regionen/': {
      id: '/regionen/'
      path: '/'
      fullPath: '/regionen/'
      preLoaderRoute: typeof RegionenIndexRouteImport
      parentRoute: typeof RegionenRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/regionen/stats': {
      id: '/regionen/stats'
      path: '/stats'
      fullPath: '/regionen/stats'
      preLoaderRoute: typeof RegionenStatsRouteImport
      parentRoute: typeof RegionenRoute
    }
    '/regionen/$regionSlug': {
      id: '/regionen/$regionSlug'
      path: '/$regionSlug'
      fullPath: '/regionen/$regionSlug'
      preLoaderRoute: typeof RegionenRegionSlugRouteImport
      parentRoute: typeof RegionenRoute
    }
    '/preview/root-fallback': {
      id: '/preview/root-fallback'
      path: '/root-fallback'
      fullPath: '/preview/root-fallback'
      preLoaderRoute: typeof PreviewRootFallbackRouteImport
      parentRoute: typeof PreviewRoute
    }
    '/preview/region-pending': {
      id: '/preview/region-pending'
      path: '/region-pending'
      fullPath: '/preview/region-pending'
      preLoaderRoute: typeof PreviewRegionPendingRouteImport
      parentRoute: typeof PreviewRoute
    }
    '/preview/region-error': {
      id: '/preview/region-error'
      path: '/region-error'
      fullPath: '/preview/region-error'
      preLoaderRoute: typeof PreviewRegionErrorRouteImport
      parentRoute: typeof PreviewRoute
    }
    '/preview/not-found': {
      id: '/preview/not-found'
      path: '/not-found'
      fullPath: '/preview/not-found'
      preLoaderRoute: typeof PreviewNotFoundRouteImport
      parentRoute: typeof PreviewRoute
    }
    '/preview/default-pending': {
      id: '/preview/default-pending'
      path: '/default-pending'
      fullPath: '/preview/default-pending'
      preLoaderRoute: typeof PreviewDefaultPendingRouteImport
      parentRoute: typeof PreviewRoute
    }
    '/preview/default-error': {
      id: '/preview/default-error'
      path: '/default-error'
      fullPath: '/preview/default-error'
      preLoaderRoute: typeof PreviewDefaultErrorRouteImport
      parentRoute: typeof PreviewRoute
    }
    '/api/uploads': {
      id: '/api/uploads'
      path: '/api/uploads'
      fullPath: '/api/uploads'
      preLoaderRoute: typeof ApiUploadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/stats': {
      id: '/api/stats'
      path: '/api/stats'
      fullPath: '/api/stats'
      preLoaderRoute: typeof ApiStatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/regions': {
      id: '/api/regions'
      path: '/api/regions'
      fullPath: '/api/regions'
      preLoaderRoute: typeof ApiRegionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/processing-dates-mapillary': {
      id: '/api/processing-dates-mapillary'
      path: '/api/processing-dates-mapillary'
      fullPath: '/api/processing-dates-mapillary'
      preLoaderRoute: typeof ApiProcessingDatesMapillaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/processing-dates': {
      id: '/api/processing-dates'
      path: '/api/processing-dates'
      fullPath: '/api/processing-dates'
      preLoaderRoute: typeof ApiProcessingDatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/map-style': {
      id: '/api/map-style'
      path: '/api/map-style'
      fullPath: '/api/map-style'
      preLoaderRoute: typeof ApiMapStyleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/campaigns': {
      id: '/api/campaigns'
      path: '/api/campaigns'
      fullPath: '/api/campaigns'
      preLoaderRoute: typeof ApiCampaignsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/boundary': {
      id: '/api/boundary'
      path: '/api/boundary'
      fullPath: '/api/boundary'
      preLoaderRoute: typeof ApiBoundaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/regions': {
      id: '/admin/regions'
      path: '/regions'
      fullPath: '/admin/regions'
      preLoaderRoute: typeof AdminRegionsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/region-contracts': {
      id: '/admin/region-contracts'
      path: '/region-contracts'
      fullPath: '/admin/region-contracts'
      preLoaderRoute: typeof AdminRegionContractsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/qa-configs': {
      id: '/admin/qa-configs'
      path: '/qa-configs'
      fullPath: '/admin/qa-configs'
      preLoaderRoute: typeof AdminQaConfigsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/processing': {
      id: '/admin/processing'
      path: '/processing'
      fullPath: '/admin/processing'
      preLoaderRoute: typeof AdminProcessingRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/memberships': {
      id: '/admin/memberships'
      path: '/memberships'
      fullPath: '/admin/memberships'
      preLoaderRoute: typeof AdminMembershipsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/map-dataset-uploads': {
      id: '/admin/map-dataset-uploads'
      path: '/map-dataset-uploads'
      fullPath: '/admin/map-dataset-uploads'
      preLoaderRoute: typeof AdminMapDatasetUploadsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/map-dataset-categories': {
      id: '/admin/map-dataset-categories'
      path: '/map-dataset-categories'
      fullPath: '/admin/map-dataset-categories'
      preLoaderRoute: typeof AdminMapDatasetCategoriesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/data-schema': {
      id: '/admin/data-schema'
      path: '/data-schema'
      fullPath: '/admin/data-schema'
      preLoaderRoute: typeof AdminDataSchemaRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/audit-log': {
      id: '/admin/audit-log'
      path: '/audit-log'
      fullPath: '/admin/audit-log'
      preLoaderRoute: typeof AdminAuditLogRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/api-tokens': {
      id: '/admin/api-tokens'
      path: '/api-tokens'
      fullPath: '/admin/api-tokens'
      preLoaderRoute: typeof AdminApiTokensRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_pages/oAuthError': {
      id: '/_pages/oAuthError'
      path: '/oAuthError'
      fullPath: '/oAuthError'
      preLoaderRoute: typeof PagesOAuthErrorRouteImport
      parentRoute: typeof PagesRoute
    }
    '/_pages/kontakt': {
      id: '/_pages/kontakt'
      path: '/kontakt'
      fullPath: '/kontakt'
      preLoaderRoute: typeof PagesKontaktRouteImport
      parentRoute: typeof PagesRoute
    }
    '/_pages/datenschutz': {
      id: '/_pages/datenschutz'
      path: '/datenschutz'
      fullPath: '/datenschutz'
      preLoaderRoute: typeof PagesDatenschutzRouteImport
      parentRoute: typeof PagesRoute
    }
    '/_pages/access-denied': {
      id: '/_pages/access-denied'
      path: '/access-denied'
      fullPath: '/access-denied'
      preLoaderRoute: typeof PagesAccessDeniedRouteImport
      parentRoute: typeof PagesRoute
    }
    '/admin/regions/': {
      id: '/admin/regions/'
      path: '/'
      fullPath: '/admin/regions/'
      preLoaderRoute: typeof AdminRegionsIndexRouteImport
      parentRoute: typeof AdminRegionsRoute
    }
    '/admin/region-contracts/': {
      id: '/admin/region-contracts/'
      path: '/'
      fullPath: '/admin/region-contracts/'
      preLoaderRoute: typeof AdminRegionContractsIndexRouteImport
      parentRoute: typeof AdminRegionContractsRoute
    }
    '/admin/qa-configs/': {
      id: '/admin/qa-configs/'
      path: '/'
      fullPath: '/admin/qa-configs/'
      preLoaderRoute: typeof AdminQaConfigsIndexRouteImport
      parentRoute: typeof AdminQaConfigsRoute
    }
    '/admin/processing/': {
      id: '/admin/processing/'
      path: '/'
      fullPath: '/admin/processing/'
      preLoaderRoute: typeof AdminProcessingIndexRouteImport
      parentRoute: typeof AdminProcessingRoute
    }
    '/admin/memberships/': {
      id: '/admin/memberships/'
      path: '/'
      fullPath: '/admin/memberships/'
      preLoaderRoute: typeof AdminMembershipsIndexRouteImport
      parentRoute: typeof AdminMembershipsRoute
    }
    '/admin/map-dataset-uploads/': {
      id: '/admin/map-dataset-uploads/'
      path: '/'
      fullPath: '/admin/map-dataset-uploads/'
      preLoaderRoute: typeof AdminMapDatasetUploadsIndexRouteImport
      parentRoute: typeof AdminMapDatasetUploadsRoute
    }
    '/admin/map-dataset-categories/': {
      id: '/admin/map-dataset-categories/'
      path: '/'
      fullPath: '/admin/map-dataset-categories/'
      preLoaderRoute: typeof AdminMapDatasetCategoriesIndexRouteImport
      parentRoute: typeof AdminMapDatasetCategoriesRoute
    }
    '/api/uploads/create': {
      id: '/api/uploads/create'
      path: '/create'
      fullPath: '/api/uploads/create'
      preLoaderRoute: typeof ApiUploadsCreateRouteImport
      parentRoute: typeof ApiUploadsRoute
    }
    '/api/uploads/$slug': {
      id: '/api/uploads/$slug'
      path: '/$slug'
      fullPath: '/api/uploads/$slug'
      preLoaderRoute: typeof ApiUploadsSlugRouteImport
      parentRoute: typeof ApiUploadsRoute
    }
    '/api/sign-in/osm': {
      id: '/api/sign-in/osm'
      path: '/api/sign-in/osm'
      fullPath: '/api/sign-in/osm'
      preLoaderRoute: typeof ApiSignInOsmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/private/warm-cache': {
      id: '/api/private/warm-cache'
      path: '/api/private/warm-cache'
      fullPath: '/api/private/warm-cache'
      preLoaderRoute: typeof ApiPrivateWarmCacheRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/private/register-sql-functions': {
      id: '/api/private/register-sql-functions'
      path: '/api/private/register-sql-functions'
      fullPath: '/api/private/register-sql-functions'
      preLoaderRoute: typeof ApiPrivateRegisterSqlFunctionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/private/regions': {
      id: '/api/private/regions'
      path: '/api/private/regions'
      fullPath: '/api/private/regions'
      preLoaderRoute: typeof ApiPrivateRegionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/private/post-processing-qa-update': {
      id: '/api/private/post-processing-qa-update'
      path: '/api/private/post-processing-qa-update'
      fullPath: '/api/private/post-processing-qa-update'
      preLoaderRoute: typeof ApiPrivatePostProcessingQaUpdateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/private/post-processing-hook': {
      id: '/api/private/post-processing-hook'
      path: '/api/private/post-processing-hook'
      fullPath: '/api/private/post-processing-hook'
      preLoaderRoute: typeof ApiPrivatePostProcessingHookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/private/generate-maproulette-tasks': {
      id: '/api/private/generate-maproulette-tasks'
      path: '/api/private/generate-maproulette-tasks'
      fullPath: '/api/private/generate-maproulette-tasks'
      preLoaderRoute: typeof ApiPrivateGenerateMaprouletteTasksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/osm-notes/rss': {
      id: '/api/osm-notes/rss'
      path: '/api/osm-notes/rss'
      fullPath: '/api/osm-notes/rss'
      preLoaderRoute: typeof ApiOsmNotesRssRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/notes/$regionSlug': {
      id: '/api/notes/$regionSlug'
      path: '/api/notes/$regionSlug'
      fullPath: '/api/notes/$regionSlug'
      preLoaderRoute: typeof ApiNotesRegionSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/regions': {
      id: '/api/admin/regions'
      path: '/api/admin/regions'
      fullPath: '/api/admin/regions'
      preLoaderRoute: typeof ApiAdminRegionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/region-uploads': {
      id: '/api/admin/region-uploads'
      path: '/api/admin/region-uploads'
      fullPath: '/api/admin/region-uploads'
      preLoaderRoute: typeof ApiAdminRegionUploadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/processing': {
      id: '/api/admin/processing'
      path: '/api/admin/processing'
      fullPath: '/api/admin/processing'
      preLoaderRoute: typeof ApiAdminProcessingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/audit-log': {
      id: '/api/admin/audit-log'
      path: '/api/admin/audit-log'
      fullPath: '/api/admin/audit-log'
      preLoaderRoute: typeof ApiAdminAuditLogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/regions/new': {
      id: '/admin/regions/new'
      path: '/new'
      fullPath: '/admin/regions/new'
      preLoaderRoute: typeof AdminRegionsNewRouteImport
      parentRoute: typeof AdminRegionsRoute
    }
    '/admin/region-contracts/new': {
      id: '/admin/region-contracts/new'
      path: '/new'
      fullPath: '/admin/region-contracts/new'
      preLoaderRoute: typeof AdminRegionContractsNewRouteImport
      parentRoute: typeof AdminRegionContractsRoute
    }
    '/admin/qa-configs/new': {
      id: '/admin/qa-configs/new'
      path: '/new'
      fullPath: '/admin/qa-configs/new'
      preLoaderRoute: typeof AdminQaConfigsNewRouteImport
      parentRoute: typeof AdminQaConfigsRoute
    }
    '/admin/processing/$metaId': {
      id: '/admin/processing/$metaId'
      path: '/$metaId'
      fullPath: '/admin/processing/$metaId'
      preLoaderRoute: typeof AdminProcessingMetaIdRouteImport
      parentRoute: typeof AdminProcessingRoute
    }
    '/admin/memberships/new': {
      id: '/admin/memberships/new'
      path: '/new'
      fullPath: '/admin/memberships/new'
      preLoaderRoute: typeof AdminMembershipsNewRouteImport
      parentRoute: typeof AdminMembershipsRoute
    }
    '/admin/map-dataset-uploads/$slug': {
      id: '/admin/map-dataset-uploads/$slug'
      path: '/$slug'
      fullPath: '/admin/map-dataset-uploads/$slug'
      preLoaderRoute: typeof AdminMapDatasetUploadsSlugRouteImport
      parentRoute: typeof AdminMapDatasetUploadsRoute
    }
    '/admin/map-dataset-categories/new': {
      id: '/admin/map-dataset-categories/new'
      path: '/new'
      fullPath: '/admin/map-dataset-categories/new'
      preLoaderRoute: typeof AdminMapDatasetCategoriesNewRouteImport
      parentRoute: typeof AdminMapDatasetCategoriesRoute
    }
    '/admin/map-dataset-categories/$categoryKey': {
      id: '/admin/map-dataset-categories/$categoryKey'
      path: '/$categoryKey'
      fullPath: '/admin/map-dataset-categories/$categoryKey'
      preLoaderRoute: typeof AdminMapDatasetCategoriesCategoryKeyRouteImport
      parentRoute: typeof AdminMapDatasetCategoriesRoute
    }
    '/_pages/settings/user': {
      id: '/_pages/settings/user'
      path: '/settings/user'
      fullPath: '/settings/user'
      preLoaderRoute: typeof PagesSettingsUserRouteImport
      parentRoute: typeof PagesRoute
    }
    '/_pages/docs/mapillary-coverage': {
      id: '/_pages/docs/mapillary-coverage'
      path: '/docs/mapillary-coverage'
      fullPath: '/docs/mapillary-coverage'
      preLoaderRoute: typeof PagesDocsMapillaryCoverageRouteImport
      parentRoute: typeof PagesRoute
    }
    '/_pages/docs/$tableName': {
      id: '/_pages/docs/$tableName'
      path: '/docs/$tableName'
      fullPath: '/docs/$tableName'
      preLoaderRoute: typeof PagesDocsTableNameRouteImport
      parentRoute: typeof PagesRoute
    }
    '/api/regions/$regionSlug/uploads-csv': {
      id: '/api/regions/$regionSlug/uploads-csv'
      path: '/$regionSlug/uploads-csv'
      fullPath: '/api/regions/$regionSlug/uploads-csv'
      preLoaderRoute: typeof ApiRegionsRegionSlugUploadsCsvRouteImport
      parentRoute: typeof ApiRegionsRoute
    }
    '/api/region-uploads/$id/$filename': {
      id: '/api/region-uploads/$id/$filename'
      path: '/api/region-uploads/$id/$filename'
      fullPath: '/api/region-uploads/$id/$filename'
      preLoaderRoute: typeof ApiRegionUploadsIdFilenameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/notes/$regionSlug/download': {
      id: '/api/notes/$regionSlug/download'
      path: '/download'
      fullPath: '/api/notes/$regionSlug/download'
      preLoaderRoute: typeof ApiNotesRegionSlugDownloadRouteImport
      parentRoute: typeof ApiNotesRegionSlugRoute
    }
    '/api/maproulette/statistic-proxy/$challengeId': {
      id: '/api/maproulette/statistic-proxy/$challengeId'
      path: '/api/maproulette/statistic-proxy/$challengeId'
      fullPath: '/api/maproulette/statistic-proxy/$challengeId'
      preLoaderRoute: typeof ApiMaprouletteStatisticProxyChallengeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/maproulette/data/test_tag_fix_two': {
      id: '/api/maproulette/data/test_tag_fix_two'
      path: '/api/maproulette/data/test_tag_fix_two'
      fullPath: '/api/maproulette/data/test_tag_fix_two'
      preLoaderRoute: typeof ApiMaprouletteDataTest_tag_fix_twoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/maproulette/data/test_tag_fix_cycleway-shared': {
      id: '/api/maproulette/data/test_tag_fix_cycleway-shared'
      path: '/api/maproulette/data/test_tag_fix_cycleway-shared'
      fullPath: '/api/maproulette/data/test_tag_fix_cycleway-shared'
      preLoaderRoute: typeof ApiMaprouletteDataTest_tag_fix_cyclewaySharedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/maproulette/data/test_tag_fix': {
      id: '/api/maproulette/data/test_tag_fix'
      path: '/api/maproulette/data/test_tag_fix'
      fullPath: '/api/maproulette/data/test_tag_fix'
      preLoaderRoute: typeof ApiMaprouletteDataTest_tag_fixRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/maproulette/data/$projectKey': {
      id: '/api/maproulette/data/$projectKey'
      path: '/api/maproulette/data/$projectKey'
      fullPath: '/api/maproulette/data/$projectKey'
      preLoaderRoute: typeof ApiMaprouletteDataProjectKeyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/export/$regionSlug/$tableName': {
      id: '/api/export/$regionSlug/$tableName'
      path: '/api/export/$regionSlug/$tableName'
      fullPath: '/api/export/$regionSlug/$tableName'
      preLoaderRoute: typeof ApiExportRegionSlugTableNameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/export-ogr/$regionSlug/$tableName': {
      id: '/api/export-ogr/$regionSlug/$tableName'
      path: '/api/export-ogr/$regionSlug/$tableName'
      fullPath: '/api/export-ogr/$regionSlug/$tableName'
      preLoaderRoute: typeof ApiExportOgrRegionSlugTableNameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/regions/$slug': {
      id: '/api/admin/regions/$slug'
      path: '/$slug'
      fullPath: '/api/admin/regions/$slug'
      preLoaderRoute: typeof ApiAdminRegionsSlugRouteImport
      parentRoute: typeof ApiAdminRegionsRoute
    }
    '/api/admin/region-uploads/upload': {
      id: '/api/admin/region-uploads/upload'
      path: '/upload'
      fullPath: '/api/admin/region-uploads/upload'
      preLoaderRoute: typeof ApiAdminRegionUploadsUploadRouteImport
      parentRoute: typeof ApiAdminRegionUploadsRoute
    }
    '/api/admin/processing/$metaId': {
      id: '/api/admin/processing/$metaId'
      path: '/$metaId'
      fullPath: '/api/admin/processing/$metaId'
      preLoaderRoute: typeof ApiAdminProcessingMetaIdRouteImport
      parentRoute: typeof ApiAdminProcessingRoute
    }
    '/api/admin/data-schema/import': {
      id: '/api/admin/data-schema/import'
      path: '/api/admin/data-schema/import'
      fullPath: '/api/admin/data-schema/import'
      preLoaderRoute: typeof ApiAdminDataSchemaImportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/regions/$regionSlug/edit': {
      id: '/admin/regions/$regionSlug/edit'
      path: '/$regionSlug/edit'
      fullPath: '/admin/regions/$regionSlug/edit'
      preLoaderRoute: typeof AdminRegionsRegionSlugEditRouteImport
      parentRoute: typeof AdminRegionsRoute
    }
    '/admin/region-contracts/$slug/edit': {
      id: '/admin/region-contracts/$slug/edit'
      path: '/$slug/edit'
      fullPath: '/admin/region-contracts/$slug/edit'
      preLoaderRoute: typeof AdminRegionContractsSlugEditRouteImport
      parentRoute: typeof AdminRegionContractsRoute
    }
    '/admin/qa-configs/$id/edit': {
      id: '/admin/qa-configs/$id/edit'
      path: '/$id/edit'
      fullPath: '/admin/qa-configs/$id/edit'
      preLoaderRoute: typeof AdminQaConfigsIdEditRouteImport
      parentRoute: typeof AdminQaConfigsRoute
    }
    '/api/admin/qa-configs/$id/export-csv': {
      id: '/api/admin/qa-configs/$id/export-csv'
      path: '/api/admin/qa-configs/$id/export-csv'
      fullPath: '/api/admin/qa-configs/$id/export-csv'
      preLoaderRoute: typeof ApiAdminQaConfigsIdExportCsvRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface PagesRouteChildren {
  PagesAccessDeniedRoute: typeof PagesAccessDeniedRoute
  PagesDatenschutzRoute: typeof PagesDatenschutzRoute
  PagesKontaktRoute: typeof PagesKontaktRoute
  PagesOAuthErrorRoute: typeof PagesOAuthErrorRoute
  PagesDocsTableNameRoute: typeof PagesDocsTableNameRoute
  PagesDocsMapillaryCoverageRoute: typeof PagesDocsMapillaryCoverageRoute
  PagesSettingsUserRoute: typeof PagesSettingsUserRoute
}

const PagesRouteChildren: PagesRouteChildren = {
  PagesAccessDeniedRoute: PagesAccessDeniedRoute,
  PagesDatenschutzRoute: PagesDatenschutzRoute,
  PagesKontaktRoute: PagesKontaktRoute,
  PagesOAuthErrorRoute: PagesOAuthErrorRoute,
  PagesDocsTableNameRoute: PagesDocsTableNameRoute,
  PagesDocsMapillaryCoverageRoute: PagesDocsMapillaryCoverageRoute,
  PagesSettingsUserRoute: PagesSettingsUserRoute,
}

const PagesRouteWithChildren = PagesRoute._addFileChildren(PagesRouteChildren)

interface AdminMapDatasetCategoriesRouteChildren {
  AdminMapDatasetCategoriesCategoryKeyRoute: typeof AdminMapDatasetCategoriesCategoryKeyRoute
  AdminMapDatasetCategoriesNewRoute: typeof AdminMapDatasetCategoriesNewRoute
  AdminMapDatasetCategoriesIndexRoute: typeof AdminMapDatasetCategoriesIndexRoute
}

const AdminMapDatasetCategoriesRouteChildren: AdminMapDatasetCategoriesRouteChildren =
  {
    AdminMapDatasetCategoriesCategoryKeyRoute:
      AdminMapDatasetCategoriesCategoryKeyRoute,
    AdminMapDatasetCategoriesNewRoute: AdminMapDatasetCategoriesNewRoute,
    AdminMapDatasetCategoriesIndexRoute: AdminMapDatasetCategoriesIndexRoute,
  }

const AdminMapDatasetCategoriesRouteWithChildren =
  AdminMapDatasetCategoriesRoute._addFileChildren(
    AdminMapDatasetCategoriesRouteChildren,
  )

interface AdminMapDatasetUploadsRouteChildren {
  AdminMapDatasetUploadsSlugRoute: typeof AdminMapDatasetUploadsSlugRoute
  AdminMapDatasetUploadsIndexRoute: typeof AdminMapDatasetUploadsIndexRoute
}

const AdminMapDatasetUploadsRouteChildren: AdminMapDatasetUploadsRouteChildren =
  {
    AdminMapDatasetUploadsSlugRoute: AdminMapDatasetUploadsSlugRoute,
    AdminMapDatasetUploadsIndexRoute: AdminMapDatasetUploadsIndexRoute,
  }

const AdminMapDatasetUploadsRouteWithChildren =
  AdminMapDatasetUploadsRoute._addFileChildren(
    AdminMapDatasetUploadsRouteChildren,
  )

interface AdminMembershipsRouteChildren {
  AdminMembershipsNewRoute: typeof AdminMembershipsNewRoute
  AdminMembershipsIndexRoute: typeof AdminMembershipsIndexRoute
}

const AdminMembershipsRouteChildren: AdminMembershipsRouteChildren = {
  AdminMembershipsNewRoute: AdminMembershipsNewRoute,
  AdminMembershipsIndexRoute: AdminMembershipsIndexRoute,
}

const AdminMembershipsRouteWithChildren =
  AdminMembershipsRoute._addFileChildren(AdminMembershipsRouteChildren)

interface AdminProcessingRouteChildren {
  AdminProcessingMetaIdRoute: typeof AdminProcessingMetaIdRoute
  AdminProcessingIndexRoute: typeof AdminProcessingIndexRoute
}

const AdminProcessingRouteChildren: AdminProcessingRouteChildren = {
  AdminProcessingMetaIdRoute: AdminProcessingMetaIdRoute,
  AdminProcessingIndexRoute: AdminProcessingIndexRoute,
}

const AdminProcessingRouteWithChildren = AdminProcessingRoute._addFileChildren(
  AdminProcessingRouteChildren,
)

interface AdminQaConfigsRouteChildren {
  AdminQaConfigsNewRoute: typeof AdminQaConfigsNewRoute
  AdminQaConfigsIndexRoute: typeof AdminQaConfigsIndexRoute
  AdminQaConfigsIdEditRoute: typeof AdminQaConfigsIdEditRoute
}

const AdminQaConfigsRouteChildren: AdminQaConfigsRouteChildren = {
  AdminQaConfigsNewRoute: AdminQaConfigsNewRoute,
  AdminQaConfigsIndexRoute: AdminQaConfigsIndexRoute,
  AdminQaConfigsIdEditRoute: AdminQaConfigsIdEditRoute,
}

const AdminQaConfigsRouteWithChildren = AdminQaConfigsRoute._addFileChildren(
  AdminQaConfigsRouteChildren,
)

interface AdminRegionContractsRouteChildren {
  AdminRegionContractsNewRoute: typeof AdminRegionContractsNewRoute
  AdminRegionContractsIndexRoute: typeof AdminRegionContractsIndexRoute
  AdminRegionContractsSlugEditRoute: typeof AdminRegionContractsSlugEditRoute
}

const AdminRegionContractsRouteChildren: AdminRegionContractsRouteChildren = {
  AdminRegionContractsNewRoute: AdminRegionContractsNewRoute,
  AdminRegionContractsIndexRoute: AdminRegionContractsIndexRoute,
  AdminRegionContractsSlugEditRoute: AdminRegionContractsSlugEditRoute,
}

const AdminRegionContractsRouteWithChildren =
  AdminRegionContractsRoute._addFileChildren(AdminRegionContractsRouteChildren)

interface AdminRegionsRouteChildren {
  AdminRegionsNewRoute: typeof AdminRegionsNewRoute
  AdminRegionsIndexRoute: typeof AdminRegionsIndexRoute
  AdminRegionsRegionSlugEditRoute: typeof AdminRegionsRegionSlugEditRoute
}

const AdminRegionsRouteChildren: AdminRegionsRouteChildren = {
  AdminRegionsNewRoute: AdminRegionsNewRoute,
  AdminRegionsIndexRoute: AdminRegionsIndexRoute,
  AdminRegionsRegionSlugEditRoute: AdminRegionsRegionSlugEditRoute,
}

const AdminRegionsRouteWithChildren = AdminRegionsRoute._addFileChildren(
  AdminRegionsRouteChildren,
)

interface AdminRouteChildren {
  AdminApiTokensRoute: typeof AdminApiTokensRoute
  AdminAuditLogRoute: typeof AdminAuditLogRoute
  AdminDataSchemaRoute: typeof AdminDataSchemaRoute
  AdminMapDatasetCategoriesRoute: typeof AdminMapDatasetCategoriesRouteWithChildren
  AdminMapDatasetUploadsRoute: typeof AdminMapDatasetUploadsRouteWithChildren
  AdminMembershipsRoute: typeof AdminMembershipsRouteWithChildren
  AdminProcessingRoute: typeof AdminProcessingRouteWithChildren
  AdminQaConfigsRoute: typeof AdminQaConfigsRouteWithChildren
  AdminRegionContractsRoute: typeof AdminRegionContractsRouteWithChildren
  AdminRegionsRoute: typeof AdminRegionsRouteWithChildren
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminApiTokensRoute: AdminApiTokensRoute,
  AdminAuditLogRoute: AdminAuditLogRoute,
  AdminDataSchemaRoute: AdminDataSchemaRoute,
  AdminMapDatasetCategoriesRoute: AdminMapDatasetCategoriesRouteWithChildren,
  AdminMapDatasetUploadsRoute: AdminMapDatasetUploadsRouteWithChildren,
  AdminMembershipsRoute: AdminMembershipsRouteWithChildren,
  AdminProcessingRoute: AdminProcessingRouteWithChildren,
  AdminQaConfigsRoute: AdminQaConfigsRouteWithChildren,
  AdminRegionContractsRoute: AdminRegionContractsRouteWithChildren,
  AdminRegionsRoute: AdminRegionsRouteWithChildren,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface PreviewRouteChildren {
  PreviewDefaultErrorRoute: typeof PreviewDefaultErrorRoute
  PreviewDefaultPendingRoute: typeof PreviewDefaultPendingRoute
  PreviewNotFoundRoute: typeof PreviewNotFoundRoute
  PreviewRegionErrorRoute: typeof PreviewRegionErrorRoute
  PreviewRegionPendingRoute: typeof PreviewRegionPendingRoute
  PreviewRootFallbackRoute: typeof PreviewRootFallbackRoute
}

const PreviewRouteChildren: PreviewRouteChildren = {
  PreviewDefaultErrorRoute: PreviewDefaultErrorRoute,
  PreviewDefaultPendingRoute: PreviewDefaultPendingRoute,
  PreviewNotFoundRoute: PreviewNotFoundRoute,
  PreviewRegionErrorRoute: PreviewRegionErrorRoute,
  PreviewRegionPendingRoute: PreviewRegionPendingRoute,
  PreviewRootFallbackRoute: PreviewRootFallbackRoute,
}

const PreviewRouteWithChildren =
  PreviewRoute._addFileChildren(PreviewRouteChildren)

interface RegionenRouteChildren {
  RegionenRegionSlugRoute: typeof RegionenRegionSlugRoute
  RegionenStatsRoute: typeof RegionenStatsRoute
  RegionenIndexRoute: typeof RegionenIndexRoute
}

const RegionenRouteChildren: RegionenRouteChildren = {
  RegionenRegionSlugRoute: RegionenRegionSlugRoute,
  RegionenStatsRoute: RegionenStatsRoute,
  RegionenIndexRoute: RegionenIndexRoute,
}

const RegionenRouteWithChildren = RegionenRoute._addFileChildren(
  RegionenRouteChildren,
)

interface ApiRegionsRouteChildren {
  ApiRegionsRegionSlugUploadsCsvRoute: typeof ApiRegionsRegionSlugUploadsCsvRoute
}

const ApiRegionsRouteChildren: ApiRegionsRouteChildren = {
  ApiRegionsRegionSlugUploadsCsvRoute: ApiRegionsRegionSlugUploadsCsvRoute,
}

const ApiRegionsRouteWithChildren = ApiRegionsRoute._addFileChildren(
  ApiRegionsRouteChildren,
)

interface ApiUploadsRouteChildren {
  ApiUploadsSlugRoute: typeof ApiUploadsSlugRoute
  ApiUploadsCreateRoute: typeof ApiUploadsCreateRoute
}

const ApiUploadsRouteChildren: ApiUploadsRouteChildren = {
  ApiUploadsSlugRoute: ApiUploadsSlugRoute,
  ApiUploadsCreateRoute: ApiUploadsCreateRoute,
}

const ApiUploadsRouteWithChildren = ApiUploadsRoute._addFileChildren(
  ApiUploadsRouteChildren,
)

interface ApiAdminProcessingRouteChildren {
  ApiAdminProcessingMetaIdRoute: typeof ApiAdminProcessingMetaIdRoute
}

const ApiAdminProcessingRouteChildren: ApiAdminProcessingRouteChildren = {
  ApiAdminProcessingMetaIdRoute: ApiAdminProcessingMetaIdRoute,
}

const ApiAdminProcessingRouteWithChildren =
  ApiAdminProcessingRoute._addFileChildren(ApiAdminProcessingRouteChildren)

interface ApiAdminRegionUploadsRouteChildren {
  ApiAdminRegionUploadsUploadRoute: typeof ApiAdminRegionUploadsUploadRoute
}

const ApiAdminRegionUploadsRouteChildren: ApiAdminRegionUploadsRouteChildren = {
  ApiAdminRegionUploadsUploadRoute: ApiAdminRegionUploadsUploadRoute,
}

const ApiAdminRegionUploadsRouteWithChildren =
  ApiAdminRegionUploadsRoute._addFileChildren(
    ApiAdminRegionUploadsRouteChildren,
  )

interface ApiAdminRegionsRouteChildren {
  ApiAdminRegionsSlugRoute: typeof ApiAdminRegionsSlugRoute
}

const ApiAdminRegionsRouteChildren: ApiAdminRegionsRouteChildren = {
  ApiAdminRegionsSlugRoute: ApiAdminRegionsSlugRoute,
}

const ApiAdminRegionsRouteWithChildren = ApiAdminRegionsRoute._addFileChildren(
  ApiAdminRegionsRouteChildren,
)

interface ApiNotesRegionSlugRouteChildren {
  ApiNotesRegionSlugDownloadRoute: typeof ApiNotesRegionSlugDownloadRoute
}

const ApiNotesRegionSlugRouteChildren: ApiNotesRegionSlugRouteChildren = {
  ApiNotesRegionSlugDownloadRoute: ApiNotesRegionSlugDownloadRoute,
}

const ApiNotesRegionSlugRouteWithChildren =
  ApiNotesRegionSlugRoute._addFileChildren(ApiNotesRegionSlugRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PagesRoute: PagesRouteWithChildren,
  AdminRoute: AdminRouteWithChildren,
  McpRoute: McpRoute,
  PreviewRoute: PreviewRouteWithChildren,
  RegionenRoute: RegionenRouteWithChildren,
  ApiBoundaryRoute: ApiBoundaryRoute,
  ApiCampaignsRoute: ApiCampaignsRoute,
  ApiMapStyleRoute: ApiMapStyleRoute,
  ApiProcessingDatesRoute: ApiProcessingDatesRoute,
  ApiProcessingDatesMapillaryRoute: ApiProcessingDatesMapillaryRoute,
  ApiRegionsRoute: ApiRegionsRouteWithChildren,
  ApiStatsRoute: ApiStatsRoute,
  ApiUploadsRoute: ApiUploadsRouteWithChildren,
  ApiAdminAuditLogRoute: ApiAdminAuditLogRoute,
  ApiAdminProcessingRoute: ApiAdminProcessingRouteWithChildren,
  ApiAdminRegionUploadsRoute: ApiAdminRegionUploadsRouteWithChildren,
  ApiAdminRegionsRoute: ApiAdminRegionsRouteWithChildren,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiNotesRegionSlugRoute: ApiNotesRegionSlugRouteWithChildren,
  ApiOsmNotesRssRoute: ApiOsmNotesRssRoute,
  ApiPrivateGenerateMaprouletteTasksRoute:
    ApiPrivateGenerateMaprouletteTasksRoute,
  ApiPrivatePostProcessingHookRoute: ApiPrivatePostProcessingHookRoute,
  ApiPrivatePostProcessingQaUpdateRoute: ApiPrivatePostProcessingQaUpdateRoute,
  ApiPrivateRegionsRoute: ApiPrivateRegionsRoute,
  ApiPrivateRegisterSqlFunctionsRoute: ApiPrivateRegisterSqlFunctionsRoute,
  ApiPrivateWarmCacheRoute: ApiPrivateWarmCacheRoute,
  ApiSignInOsmRoute: ApiSignInOsmRoute,
  ApiAdminDataSchemaImportRoute: ApiAdminDataSchemaImportRoute,
  ApiExportOgrRegionSlugTableNameRoute: ApiExportOgrRegionSlugTableNameRoute,
  ApiExportRegionSlugTableNameRoute: ApiExportRegionSlugTableNameRoute,
  ApiMaprouletteDataProjectKeyRoute: ApiMaprouletteDataProjectKeyRoute,
  ApiMaprouletteDataTest_tag_fixRoute: ApiMaprouletteDataTest_tag_fixRoute,
  ApiMaprouletteDataTest_tag_fix_cyclewaySharedRoute:
    ApiMaprouletteDataTest_tag_fix_cyclewaySharedRoute,
  ApiMaprouletteDataTest_tag_fix_twoRoute:
    ApiMaprouletteDataTest_tag_fix_twoRoute,
  ApiMaprouletteStatisticProxyChallengeIdRoute:
    ApiMaprouletteStatisticProxyChallengeIdRoute,
  ApiRegionUploadsIdFilenameRoute: ApiRegionUploadsIdFilenameRoute,
  ApiAdminQaConfigsIdExportCsvRoute: ApiAdminQaConfigsIdExportCsvRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
