// DO NOT EDIT MANUALLY
// This file was automatically generated by `scripts/MapboxStyles/process.ts`

// This type is used in `mapboxStyleLayers` and gives some visibility into what kind of data we fetch from Mapbox.
export type MapboxStyleLayer = {
  beforeId?: unknown
  filter?: unknown
  id: unknown
  layout?: unknown
  maxzoom?: unknown
  minzoom?: unknown
  paint?: unknown
  type?: unknown
}
