describe('is_valid_conditional_value', function()
  local is_valid_conditional_value = require('topics.parking.helper.is_valid_conditional_value')

  it('accepts well-formed conditional values', function()
    assert.is_true(is_valid_conditional_value('loading_only @ (Mo-Fr 08:00-18:00)'))
    assert.is_true(is_valid_conditional_value('no_parking @ (Mo-Fr 08:00-18:00; Sa 09:00-14:00)'))
    assert.is_true(is_valid_conditional_value('no_parking @ (Mo-Fr 08:00-18:00); none @ residents'))
    assert.is_true(is_valid_conditional_value('no @ (weight > 7.5 AND wet)'))
    assert.is_true(is_valid_conditional_value('1 hour @ (Mo-Fr 08:00-18:00);'))
  end)

  -- Real values from OSM Berlin (2026-09-25)
  it('rejects unbalanced brackets', function()
    assert.is_false(is_valid_conditional_value('no_parking @ (Mo-Fr 06:00-20;00, Sa 06:00-15:00)...)'))
    assert.is_false(is_valid_conditional_value('no_stopping @ (Mo-Sa 07:00-19:00; PH off)...)'))
    assert.is_false(is_valid_conditional_value('2 hours @ (Mo-Fr 08:00-19:00; Sa 08:00-14:00))'))
    assert.is_false(is_valid_conditional_value('no_parking @ (Mo-Fr 09:00-20:00; Sa 09:00-18:00; none @ residents'))
  end)

  it('rejects nested brackets and @ inside the condition', function()
    assert.is_false(is_valid_conditional_value('designated @ (@ (Mo-Fr 07:00-19:00)'))
    assert.is_false(is_valid_conditional_value('1 hour @ ((Mo-Fr 08:00-18:00))'))
    assert.is_false(is_valid_conditional_value('no_parking @ (Mo-Fr @ 08:00-18:00)'))
  end)

  it('rejects parts without value or condition', function()
    assert.is_false(is_valid_conditional_value('no_parking'))
    assert.is_false(is_valid_conditional_value('@ (Mo-Fr 08:00-18:00)'))
    assert.is_false(is_valid_conditional_value('no_parking @ ()'))
    assert.is_false(is_valid_conditional_value(''))
    assert.is_false(is_valid_conditional_value(nil))
  end)
end)
