local excluded_from_roads_tables = require('topics.roads_bikelanes.helper.excluded_from_roads_tables')

describe('excluded_from_roads_tables', function()
  it('keeps outdoor paths and motor roads that the roads writer would insert', function()
    assert.is_false(excluded_from_roads_tables({ highway = 'path' }))
    assert.is_false(excluded_from_roads_tables({ highway = 'footway' }))
    assert.is_false(excluded_from_roads_tables({ highway = 'steps' }))
    assert.is_false(excluded_from_roads_tables({ highway = 'residential' }))
  end)

  it('matches the roads writer skip for OSM sidewalks and derived sidepaths', function()
    assert.is_true(excluded_from_roads_tables({ highway = 'footway', footway = 'sidewalk' }))
    assert.is_true(excluded_from_roads_tables({ highway = 'path', path = 'sidepath' }))
    assert.is_true(excluded_from_roads_tables({ highway = 'footway', parent_road = 'residential' }))
  end)

  it('matches the roads writer skip for indoor, informal, and destination/customers access', function()
    assert.is_true(excluded_from_roads_tables({ highway = 'footway', indoor = 'yes' }))
    assert.is_true(excluded_from_roads_tables({ highway = 'steps', indoor = 'yes' }))
    assert.is_true(excluded_from_roads_tables({ highway = 'path', informal = 'yes' }))
    assert.is_true(excluded_from_roads_tables({ highway = 'footway', access = 'destination' }))
    assert.is_true(excluded_from_roads_tables({ highway = 'footway', foot = 'customers' }))
  end)
end)
