name: Deploy Staging
on:
  push:
    branches:
      - develop
      - tinkering
permissions:
  contents: read
  id-token: write

jobs:
  setup_env:
    uses: ./.github/workflows/setup-env.yml
    with:
      ENVIRONMENT: staging
    secrets: inherit
  restart_services:
    uses: ./.github/workflows/restart-services.yml
    needs: setup_env
    with:
      ENVIRONMENT: staging
    secrets: inherit
  deploy_processing:
    uses: ./.github/workflows/deploy-processing.yml
    needs: restart_services
    with:
      ENVIRONMENT: staging
      CONFIG_CHANGED: ${{ needs.restart_services.outputs.CHANGES == 'true' }}
    secrets: inherit
  deploy_app:
    uses: ./.github/workflows/deploy-app.yml
    needs: restart_services
    with:
      ENVIRONMENT: staging
      CONFIG_CHANGED: ${{ needs.restart_services.outputs.CHANGES == 'true' }}
    secrets: inherit
